export default function buildPanelSectionExtras(input = {}) {
    const p = input;
    return {
        requestJson: p.requestJson,
        activeTenantId: p.activeTenantId,
        assignmentRoleOptions: p.assignmentRoleOptions,
        buildInitials: p.buildInitials,
        toTenantDisplayName: p.toTenantDisplayName,
        toUserDisplayName: p.toUserDisplayName,
        formatDateTimeLabel: p.formatDateTimeLabel,
        normalizeCatalogIdsList: p.normalizeCatalogIdsList,
        sanitizeAiAssistantCode: p.sanitizeAiAssistantCode,
        normalizeQuickReplyMediaAssets: p.normalizeQuickReplyMediaAssets,
        resolveQuickReplyAssetPreviewUrl: p.resolveQuickReplyAssetPreviewUrl,
        isQuickReplyImageAsset: p.isQuickReplyImageAsset,
        getQuickReplyAssetTypeLabel: p.getQuickReplyAssetTypeLabel,
        getQuickReplyAssetDisplayName: p.getQuickReplyAssetDisplayName,
        formatBytes: p.formatBytes,
        chunkItems: p.chunkItems,
        PLAN_OPTIONS: p.PLAN_OPTIONS,
        AI_MODEL_OPTIONS: p.AI_MODEL_OPTIONS,
        EMPTY_AI_ASSISTANT_FORM: p.EMPTY_AI_ASSISTANT_FORM,
        DEFAULT_LABEL_COLORS: p.DEFAULT_LABEL_COLORS,
        QUICK_REPLY_ALLOWED_EXTENSIONS_LABEL: p.QUICK_REPLY_ALLOWED_EXTENSIONS_LABEL,
        QUICK_REPLY_ACCEPT_VALUE: p.QUICK_REPLY_ACCEPT_VALUE,
        MODULE_KEYS: p.MODULE_KEYS,
        CATALOG_MODE_OPTIONS: p.CATALOG_MODE_OPTIONS,
        EMPTY_TENANT_CATALOG_FORM: p.EMPTY_TENANT_CATALOG_FORM,
        buildTenantCatalogPayload: p.buildTenantCatalogPayload,
        buildCatalogProductFormFromItem: p.buildCatalogProductFormFromItem,
        PLAN_LIMIT_KEYS: p.PLAN_LIMIT_KEYS,
        PLAN_FEATURE_KEYS: p.PLAN_FEATURE_KEYS,
        sanitizeRoleCode: p.sanitizeRoleCode,
        buildCustomerPayloadFromForm: p.buildCustomerPayloadFromForm
    };
}
