import * as saasAdminPanelHelpers from '../../../helpers';
import useOperationsPanelState from '../../domains/operations/useOperationsPanelState';
import useSaasAccessControl from '../../useSaasAccessControl';
import useSaasApiClient from '../../useSaasApiClient';
import useSaasPanelCoreState from '../useSaasPanelCoreState';
import useSaasPanelLoadingState from '../useSaasPanelLoadingState';
import useSaasPanelSectionContexts from '../useSaasPanelSectionContexts';
import buildPanelSectionExtras from '../contexts/buildPanelSectionExtras';
import useSaasPanelActionContexts from './useSaasPanelActionContexts';
import useSaasAiController from './useSaasAiController';
import useSaasCatalogController from './useSaasCatalogController';
import useSaasOperationsController from './useSaasOperationsController';
import useSaasPanelDataContexts from './useSaasPanelDataContexts';
import useSaasFrameNavigationController from './useSaasFrameNavigationController';
import useSaasQuickRepliesController from './useSaasQuickRepliesController';
import useSaasTenantController from './useSaasTenantController';
import useSaasUsersController from './useSaasUsersController';
const {
    API_BASE,
    EMPTY_TENANT_FORM,
    EMPTY_USER_FORM,
    EMPTY_CUSTOMER_FORM,
    EMPTY_SETTINGS,
    EMPTY_INTEGRATIONS_FORM,
    EMPTY_TENANT_CATALOG_FORM,
    EMPTY_CATALOG_PRODUCT_FORM,
    buildCatalogProductFormFromItem,
    normalizeCatalogIdsList,
    buildTenantCatalogFormFromItem,
    buildTenantCatalogPayload,
    EMPTY_ACCESS_CATALOG,
    EMPTY_ROLE_FORM,
    PLAN_LIMIT_KEYS,
    PLAN_FEATURE_KEYS,
    EMPTY_WA_MODULE_FORM,
    EMPTY_AI_ASSISTANT_FORM,
    BASE_ROLE_OPTIONS,
    PLAN_OPTIONS,
    CATALOG_MODE_OPTIONS,
    MODULE_KEYS,
    ADMIN_NAV_ITEMS,
    AI_PROVIDER_OPTIONS,
    AI_MODEL_OPTIONS,
    LAVITAT_FIRST_ASSISTANT_SYSTEM_PROMPT,
    ROLE_PRIORITY,
    PERMISSION_OWNER_ASSIGN,
    PERMISSION_PLATFORM_OVERVIEW_READ,
    PERMISSION_PLATFORM_TENANTS_MANAGE,
    PERMISSION_PLATFORM_PLANS_MANAGE,
    PERMISSION_TENANT_OVERVIEW_READ,
    PERMISSION_TENANT_USERS_MANAGE,
    PERMISSION_TENANT_SETTINGS_READ,
    PERMISSION_TENANT_SETTINGS_MANAGE,
    PERMISSION_TENANT_INTEGRATIONS_READ,
    PERMISSION_TENANT_INTEGRATIONS_MANAGE,
    PERMISSION_TENANT_MODULES_READ,
    PERMISSION_TENANT_MODULES_MANAGE,
    PERMISSION_TENANT_QUICK_REPLIES_READ,
    PERMISSION_TENANT_QUICK_REPLIES_MANAGE,
    PERMISSION_TENANT_LABELS_READ,
    PERMISSION_TENANT_LABELS_MANAGE,
    PERMISSION_TENANT_AI_READ,
    PERMISSION_TENANT_AI_MANAGE,
    PERMISSION_TENANT_CUSTOMERS_READ,
    PERMISSION_TENANT_CUSTOMERS_MANAGE,
    PERMISSION_TENANT_CATALOGS_MANAGE,
    PERMISSION_TENANT_CHAT_ASSIGNMENTS_READ,
    PERMISSION_TENANT_CHAT_ASSIGNMENTS_MANAGE,
    PERMISSION_TENANT_KPIS_READ,
    QUICK_REPLY_ALLOWED_EXTENSIONS,
    QUICK_REPLY_ALLOWED_EXTENSIONS_LABEL,
    QUICK_REPLY_ACCEPT_VALUE,
    QUICK_REPLY_DEFAULT_MAX_UPLOAD_MB,
    QUICK_REPLY_DEFAULT_STORAGE_MB,
    EMPTY_QUICK_REPLY_LIBRARY_FORM,
    EMPTY_QUICK_REPLY_ITEM_FORM,
    DEFAULT_LABEL_COLORS,
    EMPTY_LABEL_FORM,
    normalizeQuickReplyMediaAsset,
    normalizeQuickReplyMediaAssets,
    resolveQuickReplyAssetPreviewUrl,
    isQuickReplyImageAsset,
    getQuickReplyAssetTypeLabel,
    getQuickReplyAssetDisplayName,
    normalizeTenantLabelColor,
    buildTenantLabelPayload,
    sanitizeMemberships,
    resolvePrimaryRoleFromMemberships,
    getRolePriority,
    sanitizeAiAssistantCode,
    buildAiAssistantFormFromItem,
    buildIntegrationsUpdatePayload,
    normalizePlanForm,
    sanitizeRoleCode,
    buildTenantFormFromItem,
    buildUserFormFromItem,
    normalizeCustomerFormFromItem,
    buildCustomerPayloadFromForm,
    formatDateTimeLabel,
    toTenantDisplayName,
    toUserDisplayName,
    buildInitials,
    formatBytes,
    chunkItems
} = saasAdminPanelHelpers;

export default function useSaasAdminPanelController({
    isOpen = false,
    onClose,
    onLogout,
    onOpenWhatsAppOperation,
    buildApiHeaders,
    activeTenantId = '',
    preferredTenantId = '',
    launchSource = '',
    canManageSaas = false,
    initialSection = 'saas_resumen',
    userRole = 'seller',
    isSuperAdmin = false,
    embedded = false,
    activeSection = '',
    showNavigation = true,
    showHeader = true,
    closeLabel = 'Cerrar sesion',
    currentUser = null,
}) {
    const panelCoreState = useSaasPanelCoreState({
        activeSection,
        initialSection,
        EMPTY_TENANT_FORM,
        EMPTY_USER_FORM,
        EMPTY_CUSTOMER_FORM,
        EMPTY_SETTINGS,
        EMPTY_INTEGRATIONS_FORM,
        EMPTY_TENANT_CATALOG_FORM,
        EMPTY_CATALOG_PRODUCT_FORM,
        EMPTY_WA_MODULE_FORM,
        EMPTY_AI_ASSISTANT_FORM,
        EMPTY_ACCESS_CATALOG,
        EMPTY_ROLE_FORM,
        normalizePlanForm,
        EMPTY_QUICK_REPLY_LIBRARY_FORM,
        EMPTY_QUICK_REPLY_ITEM_FORM,
        EMPTY_LABEL_FORM
    });

    const {
        waModules,
        setWaModules,
        waModuleForm,
        setWaModuleForm,
        editingWaModuleId,
        setEditingWaModuleId,
        selectedWaModuleId,
        setSelectedWaModuleId,
        moduleQuickReplyLibraryDraft,
        setModuleQuickReplyLibraryDraft,
        selectedConfigKey,
        setSelectedConfigKey,
        moduleUserPickerId,
        setModuleUserPickerId,
        tenantSettingsPanelMode,
        setTenantSettingsPanelMode,
        waModulePanelMode,
        setWaModulePanelMode,
        planMatrix,
        setPlanMatrix,
        selectedPlanId,
        setSelectedPlanId,
        planForm,
        setPlanForm,
        planPanelMode,
        setPlanPanelMode,
        accessCatalog,
        setAccessCatalog,
        loadingAccessCatalog,
        setLoadingAccessCatalog,
        selectedRoleKey,
        setSelectedRoleKey,
        roleForm,
        setRoleForm,
        rolePanelMode,
        setRolePanelMode,
        tenantLabels,
        setTenantLabels,
        selectedLabelId,
        setSelectedLabelId,
        labelForm,
        setLabelForm,
        labelPanelMode,
        setLabelPanelMode,
        labelSearch,
        setLabelSearch,
        loadingLabels,
        setLoadingLabels,
        customers,
        setCustomers,
        selectedCustomerId,
        setSelectedCustomerId,
        customerForm,
        setCustomerForm,
        customerPanelMode,
        setCustomerPanelMode,
        customerSearch,
        setCustomerSearch,
        customerCsvText,
        setCustomerCsvText,
        customerImportModuleId,
        setCustomerImportModuleId,
        busy,
        setBusy,
        loadingPlans,
        setLoadingPlans,
        error,
        setError,
        currentSection,
        setCurrentSection
    } = panelCoreState;
    const saasAccessControl = useSaasAccessControl({
        userRole,
        isSuperAdmin,
        currentUser,
        accessCatalog,
        selectedRoleKey,
        baseRoleOptions: BASE_ROLE_OPTIONS,
        getRolePriority,
        permissionKeys: {
            PERMISSION_OWNER_ASSIGN,
            PERMISSION_PLATFORM_OVERVIEW_READ,
            PERMISSION_PLATFORM_TENANTS_MANAGE,
            PERMISSION_PLATFORM_PLANS_MANAGE,
            PERMISSION_TENANT_USERS_MANAGE,
            PERMISSION_TENANT_SETTINGS_READ,
            PERMISSION_TENANT_SETTINGS_MANAGE,
            PERMISSION_TENANT_MODULES_READ,
            PERMISSION_TENANT_MODULES_MANAGE,
            PERMISSION_TENANT_QUICK_REPLIES_READ,
            PERMISSION_TENANT_QUICK_REPLIES_MANAGE,
            PERMISSION_TENANT_LABELS_READ,
            PERMISSION_TENANT_LABELS_MANAGE,
            PERMISSION_TENANT_AI_READ,
            PERMISSION_TENANT_AI_MANAGE,
            PERMISSION_TENANT_CUSTOMERS_READ,
            PERMISSION_TENANT_CUSTOMERS_MANAGE,
            PERMISSION_TENANT_CATALOGS_MANAGE,
            PERMISSION_TENANT_CHAT_ASSIGNMENTS_READ,
            PERMISSION_TENANT_CHAT_ASSIGNMENTS_MANAGE,
            PERMISSION_TENANT_KPIS_READ,
            PERMISSION_TENANT_INTEGRATIONS_READ,
            PERMISSION_TENANT_INTEGRATIONS_MANAGE
        }
    });

    const {
        normalizedRole,
        actorRoleForPolicy,
        actorRolePriority,
        currentUserId,
        canManageTenants,
        canManageUsers,
        canManageTenantSettings,
        canViewTenantSettings,
        canManageCatalog,
        canManageRoles,
        canViewSuperAdminSections,
        canEditTenantSettings,
        canEditModules,
        canViewModules,
        canManageQuickReplies,
        canViewQuickReplies,
        canManageLabels,
        canViewLabels,
        canViewAi,
        canManageAi,
        canViewCustomers,
        canManageCustomers,
        canViewOperations,
        canManageAssignments,
        canEditCatalog,
        requiresTenantSelection,
        canActorManageRoleChanges,
        roleOptions,
        canEditOptionalAccess,
        accessPackOptions,
        accessPackLabelMap,
        getOptionalPermissionKeysForRole,
        getAllowedPackIdsForRole,
        roleProfiles,
        roleLabelMap,
        selectedRoleProfile,
        permissionLabelMap,
        rolePermissionOptions,
        hasAccessCatalogData
    } = saasAccessControl;
    const { pendingRequests, requestJson } = useSaasApiClient({
        apiBase: API_BASE,
        buildApiHeaders
    });

    const operationsPanelState = useOperationsPanelState({
        canViewOperations,
        buildApiHeaders
    });
    const {
        operationsActions
    } = useSaasOperationsController({
        operationsPanelState
    });
    const panelLoadingState = useSaasPanelLoadingState({
        busy,
        error,
        overview: panelCoreState.overview,
        pendingRequests
    });
    const {
        showPanelLoading,
        aiUsageByTenant
    } = panelLoadingState;

    const {
        tenantScopeState,
        tenantDataLoaders,
        panelUserScopeState,
        panelDerivedData,
        tenantUsersState
    } = useSaasPanelDataContexts({
        overviewTenants: panelCoreState.overview.tenants,
        overviewUsers: panelCoreState.overview.users,
        selectedTenantId: panelCoreState.selectedTenantId,
        selectedUserId: panelCoreState.selectedUserId,
        settingsTenantId: panelCoreState.settingsTenantId,
        requiresTenantSelection,
        activeTenantId,
        toTenantDisplayName,
        currentUser,
        actorRoleForPolicy,
        requestJson,
        setOverview: panelCoreState.setOverview,
        setSelectedTenantId: panelCoreState.setSelectedTenantId,
        setSettingsTenantId: panelCoreState.setSettingsTenantId,
        setSelectedUserId: panelCoreState.setSelectedUserId,
        setLoadingSettings: panelCoreState.setLoadingSettings,
        setTenantSettings: panelCoreState.setTenantSettings,
        setLoadingIntegrations: panelCoreState.setLoadingIntegrations,
        setTenantIntegrations: panelCoreState.setTenantIntegrations,
        setWaModules,
        setSelectedWaModuleId,
        setCustomers,
        setSelectedCustomerId,
        currentUserId,
        actorRolePriority,
        canManageUsers,
        canActorManageRoleChanges,
        canEditOptionalAccess,
        userPanelMode: panelCoreState.userPanelMode,
        userFormRole: panelCoreState.userForm.role,
        canManageTenants,
        canManageCatalog,
        canManageLabels,
        canManageTenantSettings,
        canEditModules,
        canViewSuperAdminSections,
        resolvePrimaryRoleFromMemberships,
        sanitizeMemberships,
        getRolePriority,
        getOptionalPermissionKeysForRole,
        getAllowedPackIdsForRole,
        customerSearch,
        customers,
        waModules,
        selectedWaModuleId,
        quickReplyModuleFilterId: panelCoreState.quickReplyModuleFilterId,
        quickReplyLibraries: panelCoreState.quickReplyLibraries,
        selectedQuickReplyLibraryId: panelCoreState.selectedQuickReplyLibraryId,
        quickReplyItems: panelCoreState.quickReplyItems,
        selectedQuickReplyItemId: panelCoreState.selectedQuickReplyItemId,
        quickReplyItemForm: panelCoreState.quickReplyItemForm,
        quickReplyLibrarySearch: panelCoreState.quickReplyLibrarySearch,
        quickReplyItemSearch: panelCoreState.quickReplyItemSearch,
        tenantLabels,
        selectedLabelId,
        labelSearch,
        planMatrix,
        quickReplyDefaultMaxUploadMb: QUICK_REPLY_DEFAULT_MAX_UPLOAD_MB,
        quickReplyDefaultStorageMb: QUICK_REPLY_DEFAULT_STORAGE_MB,
        selectedConfigKey,
        waModuleForm,
        tenantCatalogs: panelCoreState.tenantCatalogs,
        selectedCatalogId: panelCoreState.selectedCatalogId,
        tenantCatalogProducts: panelCoreState.tenantCatalogProducts,
        selectedCatalogProductId: panelCoreState.selectedCatalogProductId,
        tenantAiAssistants: panelCoreState.tenantAiAssistants,
        selectedAiAssistantId: panelCoreState.selectedAiAssistantId,
        selectedPlanId,
        planOptions: PLAN_OPTIONS,
        toUserDisplayName
    });
    const {
        tenantState,
        tenantDerived,
        tenantLoaders
    } = useSaasTenantController({
        panelCoreState,
        tenantScopeState,
        tenantDataLoaders
    });
    const {
        filteredCustomers,
        selectedCustomer,
        selectedWaModule,
        tenantLabelItems,
        selectedTenantLabel,
        visibleTenantLabels,
        selectedSettingsTenant,
        selectedConfigModule,
        activeQuickReplyLibraries,
        moduleQuickReplySourceModuleId,
        moduleQuickReplyAssignedLibraries,
        moduleQuickReplyAssignedLibraryIds,
        planIds,
        selectedPlan
    } = panelDerivedData;
    const {
        catalogState,
        catalogDerived
    } = useSaasCatalogController({
        panelCoreState,
        panelDerivedData
    });
    const {
        quickRepliesState,
        quickRepliesDerived
    } = useSaasQuickRepliesController({
        panelCoreState,
        panelDerivedData
    });
    const {
        aiState,
        aiDerived
    } = useSaasAiController({
        panelCoreState,
        panelDerivedData
    });
    const {
        usersState,
        usersDerived
    } = useSaasUsersController({
        panelCoreState,
        panelUserScopeState,
        tenantUsersState
    });
    const scrollToSection = (sectionId, behavior = 'smooth') => {
        const cleanSection = String(sectionId || '').trim();
        if (!cleanSection) return;
        const node = document.getElementById(cleanSection);
        if (node && typeof node.scrollIntoView === 'function') {
            node.scrollIntoView({ behavior, block: 'start' });
        }
    };
    const {
        quickReplyAssetsUploadState,
        quickReplyAdminActions,
        tenantLabelsAdminActions,
        catalogAdminActions,
        aiAssistantsAdminActions,
        plansRolesActions,
        tenantsUsersActions,
        customersAdminActions,
        panelNavigation,
        assignmentRoleOptions,
        operationAccess,
        moduleSectionActions,
        lifecycleState
    } = useSaasPanelActionContexts({
        requestJson,
        settingsTenantId: tenantState.settingsTenantId,
        selectedQuickReplyLibrary: quickRepliesDerived.selectedQuickReplyLibrary,
        quickReplyUploadMaxBytes: quickRepliesDerived.quickReplyUploadMaxBytes,
        quickReplyUploadMaxMb: quickRepliesDerived.quickReplyUploadMaxMb,
        setQuickReplyItemForm: quickRepliesState.setQuickReplyItemForm,
        waModules,
        selectedQuickReplyLibraryId: quickRepliesState.selectedQuickReplyLibraryId,
        selectedQuickReplyItem: quickRepliesDerived.selectedQuickReplyItem,
        selectedQuickReplyItemId: quickRepliesState.selectedQuickReplyItemId,
        quickReplyScopeModuleId: quickRepliesDerived.quickReplyScopeModuleId,
        quickReplyLibraryForm: quickRepliesState.quickReplyLibraryForm,
        quickReplyItemForm: quickRepliesState.quickReplyItemForm,
        quickReplyLibraryPanelMode: quickRepliesState.quickReplyLibraryPanelMode,
        quickReplyItemPanelMode: quickRepliesState.quickReplyItemPanelMode,
        emptyQuickReplyLibraryForm: EMPTY_QUICK_REPLY_LIBRARY_FORM,
        emptyQuickReplyItemForm: EMPTY_QUICK_REPLY_ITEM_FORM,
        setQuickReplyLibraries: quickRepliesState.setQuickReplyLibraries,
        setQuickReplyItems: quickRepliesState.setQuickReplyItems,
        setSelectedQuickReplyLibraryId: quickRepliesState.setSelectedQuickReplyLibraryId,
        setSelectedQuickReplyItemId: quickRepliesState.setSelectedQuickReplyItemId,
        setQuickReplyModuleFilterId: quickRepliesState.setQuickReplyModuleFilterId,
        setQuickReplyLibraryForm: quickRepliesState.setQuickReplyLibraryForm,
        setQuickReplyLibraryPanelMode: quickRepliesState.setQuickReplyLibraryPanelMode,
        setQuickReplyItemPanelMode: quickRepliesState.setQuickReplyItemPanelMode,
        setLoadingQuickReplies: quickRepliesState.setLoadingQuickReplies,
        selectedTenantLabel,
        selectedLabelId,
        labelForm,
        labelPanelMode,
        emptyLabelForm: EMPTY_LABEL_FORM,
        defaultLabelColors: DEFAULT_LABEL_COLORS,
        setTenantLabels,
        setLabelForm,
        setLabelPanelMode,
        setLoadingLabels,
        canEditCatalog,
        selectedTenantCatalog: catalogDerived.selectedTenantCatalog,
        selectedCatalogProduct: catalogDerived.selectedCatalogProduct,
        selectedCatalogProductId: catalogState.selectedCatalogProductId,
        catalogProductForm: catalogState.catalogProductForm,
        catalogProductPanelMode: catalogState.catalogProductPanelMode,
        emptyCatalogProductForm: EMPTY_CATALOG_PRODUCT_FORM,
        emptyTenantCatalogForm: EMPTY_TENANT_CATALOG_FORM,
        setTenantCatalogs: catalogState.setTenantCatalogs,
        setSelectedCatalogId: catalogState.setSelectedCatalogId,
        setTenantCatalogForm: catalogState.setTenantCatalogForm,
        setTenantCatalogProducts: catalogState.setTenantCatalogProducts,
        setCatalogProductForm: catalogState.setCatalogProductForm,
        setCatalogProductPanelMode: catalogState.setCatalogProductPanelMode,
        setCatalogProductImageError: catalogState.setCatalogProductImageError,
        setCatalogProductImageUploading: catalogState.setCatalogProductImageUploading,
        setLoadingTenantCatalogs: catalogState.setLoadingTenantCatalogs,
        setLoadingCatalogProducts: catalogState.setLoadingCatalogProducts,
        setCatalogPanelMode: catalogState.setCatalogPanelMode,
        canManageAi,
        selectedAiAssistant: aiDerived.selectedAiAssistant,
        selectedAiAssistantId: aiState.selectedAiAssistantId,
        aiAssistantForm: aiState.aiAssistantForm,
        aiAssistantPanelMode: aiState.aiAssistantPanelMode,
        tenantIntegrations: tenantState.tenantIntegrations,
        emptyAiAssistantForm: EMPTY_AI_ASSISTANT_FORM,
        setLoadingAiAssistants: aiState.setLoadingAiAssistants,
        setTenantAiAssistants: aiState.setTenantAiAssistants,
        setAiAssistantForm: aiState.setAiAssistantForm,
        canManageRoles,
        selectedRoleProfile,
        selectedRoleKey,
        roleForm,
        rolePanelMode,
        selectedPlanId,
        planMatrix,
        planOptions: PLAN_OPTIONS,
        emptyRoleForm: EMPTY_ROLE_FORM,
        setLoadingPlans,
        setPlanMatrix,
        setPlanForm,
        setPlanPanelMode,
        setRolePanelMode,
        setLoadingAccessCatalog,
        setAccessCatalog,
        setRoleForm,
        loadingAccessCatalog,
        accessCatalog,
        canEditSelectedUser: usersDerived.canEditSelectedUser,
        selectedTenant: tenantDerived.selectedTenant,
        selectedUser: usersDerived.selectedUser,
        tenantScopeId: tenantDerived.tenantScopeId,
        selectedTenantId: tenantState.selectedTenantId,
        tenantOptions: tenantDerived.tenantOptions,
        roleOptions,
        emptyTenantForm: EMPTY_TENANT_FORM,
        emptyUserForm: EMPTY_USER_FORM,
        setTenantPanelMode: tenantState.setTenantPanelMode,
        setSettingsTenantId: tenantState.setSettingsTenantId,
        setTenantForm: tenantState.setTenantForm,
        setUserPanelMode: usersState.setUserPanelMode,
        setSelectedUserId: usersState.setSelectedUserId,
        setMembershipDraft: usersState.setMembershipDraft,
        setUserForm: usersState.setUserForm,
        customerImportModuleId,
        emptyCustomerForm: EMPTY_CUSTOMER_FORM,
        setCustomerPanelMode,
        setCustomerForm,
        navItems: ADMIN_NAV_ITEMS,
        currentSection,
        activeSection,
        initialSection,
        canManageTenants,
        canManageUsers,
        canViewCustomers,
        canViewOperations,
        canViewAi,
        canViewLabels,
        canViewQuickReplies,
        canViewModules,
        canManageCatalog,
        canViewSuperAdminSections,
        canViewTenantSettings,
        requiresTenantSelection,
        activeTenantId,
        onOpenWhatsAppOperation,
        canEditTenantSettings,
        canEditModules,
        selectedConfigModule,
        activeCatalogOptions: catalogDerived.activeCatalogOptions,
        defaultAiAssistantId: aiDerived.defaultAiAssistantId,
        setSelectedConfigKey,
        setSelectedRoleKey,
        setSelectedWaModuleId,
        setTenantSettingsPanelMode,
        setWaModulePanelMode,
        setModuleUserPickerId,
        setModuleQuickReplyLibraryDraft,
        emptyWaModuleForm: EMPTY_WA_MODULE_FORM,
        emptyIntegrationsForm: EMPTY_INTEGRATIONS_FORM,
        normalizePlanForm,
        setWaModuleForm,
        setSelectedCustomerId,
        setCustomerSearch,
        setCustomerCsvText,
        setCustomerImportModuleId,
        setSelectedAiAssistantId: aiState.setSelectedAiAssistantId,
        setCurrentSection,
        isOpen,
        canManageSaas,
        setError,
        setBusy,
        refreshOverview: tenantLoaders.refreshOverview,
        loadTenantSettings: tenantLoaders.loadTenantSettings,
        loadWaModules: tenantLoaders.loadWaModules,
        loadTenantIntegrations: tenantLoaders.loadTenantIntegrations,
        loadCustomers: tenantLoaders.loadCustomers,
        loadTenantAssignmentRules: operationsActions.loadTenantAssignmentRules,
        loadTenantOperationsKpis: operationsActions.loadTenantOperationsKpis,
        selectedWaModuleId,
        selectedConfigKey,
        selectedCatalogId: catalogState.selectedCatalogId,
        tenantSettingsPanelMode,
        waModulePanelMode,
        catalogPanelMode: catalogState.catalogPanelMode,
        planPanelMode,
        customerPanelMode,
        labelSearch,
        launchSource,
        preferredTenantId,
        resetOperationsState: operationsActions.resetOperationsState,
        setLabelSearch,
        catalogProductImageError: catalogState.catalogProductImageError,
        editingWaModuleId,
        buildTenantFormFromItem,
        buildUserFormFromItem,
        normalizeCustomerFormFromItem,
        buildAiAssistantFormFromItem,
        buildTenantCatalogFormFromItem,
        normalizeQuickReplyMediaAssets,
        scrollToSection
    });
    const {
        runAction,
        handleOpenOperation,
        handleFormImageUpload,
        openTenantFromUserMembership,
        openUserFromTenant
    } = lifecycleState;
    const quickRepliesController = {
        quickRepliesState,
        quickRepliesDerived,
        quickRepliesActions: quickReplyAdminActions,
        quickRepliesUploadState: quickReplyAssetsUploadState
    };
    const aiController = {
        aiState,
        aiDerived,
        aiActions: aiAssistantsAdminActions
    };
    const usersController = {
        usersState,
        usersDerived,
        usersActions: tenantsUsersActions
    };
    const operationsController = useSaasOperationsController({
        operationsPanelState,
        operationAccess,
        assignmentRoleOptions
    });
    const {
        selectedSectionId,
        sharedHeaderProps,
        frameProps
    } = useSaasFrameNavigationController({
        panelNavigation,
        operationAccess: operationsController.operationsDerived.operationAccess,
        moduleSectionActions,
        lifecycleState,
        onLogout,
        onClose,
        setSettingsTenantId: tenantState.setSettingsTenantId,
        setSelectedTenantId: tenantState.setSelectedTenantId,
        embedded,
        showHeader,
        busy,
        currentUserAvatarUrl: tenantDerived.currentUserAvatarUrl,
        currentUserDisplayName: tenantDerived.currentUserDisplayName,
        currentUserRoleLabel: tenantDerived.currentUserRoleLabel,
        buildInitials,
        closeLabel,
        activeTenantLabel: tenantDerived.activeTenantLabel,
        error,
        showPanelLoading,
        requiresTenantSelection,
        settingsTenantId: tenantState.settingsTenantId,
        tenantOptions: tenantDerived.tenantOptions,
        toTenantDisplayName,
        showNavigation,
        tenantScopeLocked: tenantDerived.tenantScopeLocked
    });

    const sectionContextsInput = {
        panelCoreState,
        saasAccessControl,
        operationsPanelState,
        panelLoadingState,
        tenantScopeState,
        tenantDataLoaders,
        panelUserScopeState,
        panelDerivedData,
        tenantUsersState,
        quickReplyAssetsUploadState: quickRepliesController.quickRepliesUploadState,
        quickReplyAdminActions: quickRepliesController.quickRepliesActions,
        tenantLabelsAdminActions,
        catalogAdminActions,
        aiAssistantsAdminActions: aiController.aiActions,
        plansRolesActions,
        tenantsUsersActions: usersController.usersActions,
        customersAdminActions,
        panelNavigation,
        operationAccess: operationsController.operationsDerived.operationAccess,
        moduleSectionActions,
        lifecycleState,
        extras: buildPanelSectionExtras({
            selectedSectionId,
            requestJson,
            runAction,
            activeTenantId,
            assignmentRoleOptions: operationsController.assignmentRoleOptions,
            handleOpenOperation,
            handleFormImageUpload,
            openTenantFromUserMembership,
            openUserFromTenant,
            buildInitials,
            toTenantDisplayName,
            toUserDisplayName,
            formatDateTimeLabel,
            normalizeCatalogIdsList,
            sanitizeAiAssistantCode,
            normalizeQuickReplyMediaAssets,
            resolveQuickReplyAssetPreviewUrl,
            isQuickReplyImageAsset,
            getQuickReplyAssetTypeLabel,
            getQuickReplyAssetDisplayName,
            formatBytes,
            chunkItems,
            PLAN_OPTIONS,
            AI_MODEL_OPTIONS,
            EMPTY_AI_ASSISTANT_FORM,
            DEFAULT_LABEL_COLORS,
            QUICK_REPLY_ALLOWED_EXTENSIONS_LABEL,
            QUICK_REPLY_ACCEPT_VALUE,
            MODULE_KEYS,
            CATALOG_MODE_OPTIONS,
            EMPTY_TENANT_CATALOG_FORM,
            buildTenantCatalogPayload,
            buildCatalogProductFormFromItem,
            PLAN_LIMIT_KEYS,
            PLAN_FEATURE_KEYS,
            sanitizeRoleCode,
            buildCustomerPayloadFromForm
        })
    };

    const {
        entitySectionsContext,
        opsAndAutomationSectionsContext,
        configAndGovernanceSectionsContext
    } = useSaasPanelSectionContexts(sectionContextsInput);

    return {
        isOpen,
        canManageSaas,
        selectedSectionId,
        sharedHeaderProps,
        frameProps,
        entitySectionsContext,
        opsAndAutomationSectionsContext,
        configAndGovernanceSectionsContext
    };
}





