import * as saasAdminPanelHelpers from '../../../helpers';
import useOperationsPanelState from '../../domains/operations/useOperationsPanelState';
import useSaasAccessControl from '../../useSaasAccessControl';
import useSaasApiClient from '../../useSaasApiClient';
import useSaasPanelCoreState from '../useSaasPanelCoreState';
import useSaasPanelLoadingState from '../useSaasPanelLoadingState';
import useSaasPanelSectionContexts from '../useSaasPanelSectionContexts';
import buildPanelSectionExtras from '../contexts/buildPanelSectionExtras';
import useSaasPanelActionContexts from './useSaasPanelActionContexts';
import useSaasCatalogController from './useSaasCatalogController';
import useSaasPanelDataContexts from './useSaasPanelDataContexts';
import useSaasFrameNavigationController from './useSaasFrameNavigationController';
const {
    API_BASE,
    EMPTY_TENANT_FORM,
    EMPTY_USER_FORM,
    EMPTY_CUSTOMER_FORM,
    EMPTY_SETTINGS,
    EMPTY_INTEGRATIONS_FORM,
    EMPTY_TENANT_CATALOG_FORM,
    EMPTY_CATALOG_PRODUCT_FORM,
    buildCatalogProductFormFromItem,
    normalizeCatalogIdsList,
    buildTenantCatalogFormFromItem,
    buildTenantCatalogPayload,
    EMPTY_ACCESS_CATALOG,
    EMPTY_ROLE_FORM,
    PLAN_LIMIT_KEYS,
    PLAN_FEATURE_KEYS,
    EMPTY_WA_MODULE_FORM,
    EMPTY_AI_ASSISTANT_FORM,
    BASE_ROLE_OPTIONS,
    PLAN_OPTIONS,
    CATALOG_MODE_OPTIONS,
    MODULE_KEYS,
    ADMIN_NAV_ITEMS,
    AI_PROVIDER_OPTIONS,
    AI_MODEL_OPTIONS,
    LAVITAT_FIRST_ASSISTANT_SYSTEM_PROMPT,
    ROLE_PRIORITY,
    PERMISSION_OWNER_ASSIGN,
    PERMISSION_PLATFORM_OVERVIEW_READ,
    PERMISSION_PLATFORM_TENANTS_MANAGE,
    PERMISSION_PLATFORM_PLANS_MANAGE,
    PERMISSION_TENANT_OVERVIEW_READ,
    PERMISSION_TENANT_USERS_MANAGE,
    PERMISSION_TENANT_SETTINGS_READ,
    PERMISSION_TENANT_SETTINGS_MANAGE,
    PERMISSION_TENANT_INTEGRATIONS_READ,
    PERMISSION_TENANT_INTEGRATIONS_MANAGE,
    PERMISSION_TENANT_MODULES_READ,
    PERMISSION_TENANT_MODULES_MANAGE,
    PERMISSION_TENANT_QUICK_REPLIES_READ,
    PERMISSION_TENANT_QUICK_REPLIES_MANAGE,
    PERMISSION_TENANT_LABELS_READ,
    PERMISSION_TENANT_LABELS_MANAGE,
    PERMISSION_TENANT_AI_READ,
    PERMISSION_TENANT_AI_MANAGE,
    PERMISSION_TENANT_CUSTOMERS_READ,
    PERMISSION_TENANT_CUSTOMERS_MANAGE,
    PERMISSION_TENANT_CATALOGS_MANAGE,
    PERMISSION_TENANT_CHAT_ASSIGNMENTS_READ,
    PERMISSION_TENANT_CHAT_ASSIGNMENTS_MANAGE,
    PERMISSION_TENANT_KPIS_READ,
    QUICK_REPLY_ALLOWED_EXTENSIONS,
    QUICK_REPLY_ALLOWED_EXTENSIONS_LABEL,
    QUICK_REPLY_ACCEPT_VALUE,
    QUICK_REPLY_DEFAULT_MAX_UPLOAD_MB,
    QUICK_REPLY_DEFAULT_STORAGE_MB,
    EMPTY_QUICK_REPLY_LIBRARY_FORM,
    EMPTY_QUICK_REPLY_ITEM_FORM,
    DEFAULT_LABEL_COLORS,
    EMPTY_LABEL_FORM,
    normalizeQuickReplyMediaAsset,
    normalizeQuickReplyMediaAssets,
    resolveQuickReplyAssetPreviewUrl,
    isQuickReplyImageAsset,
    getQuickReplyAssetTypeLabel,
    getQuickReplyAssetDisplayName,
    normalizeTenantLabelColor,
    buildTenantLabelPayload,
    sanitizeMemberships,
    resolvePrimaryRoleFromMemberships,
    getRolePriority,
    sanitizeAiAssistantCode,
    buildAiAssistantFormFromItem,
    buildIntegrationsUpdatePayload,
    normalizePlanForm,
    sanitizeRoleCode,
    buildTenantFormFromItem,
    buildUserFormFromItem,
    normalizeCustomerFormFromItem,
    buildCustomerPayloadFromForm,
    formatDateTimeLabel,
    toTenantDisplayName,
    toUserDisplayName,
    buildInitials,
    formatBytes,
    chunkItems
} = saasAdminPanelHelpers;

export default function useSaasAdminPanelController({
    isOpen = false,
    onClose,
    onLogout,
    onOpenWhatsAppOperation,
    buildApiHeaders,
    activeTenantId = '',
    preferredTenantId = '',
    launchSource = '',
    canManageSaas = false,
    initialSection = 'saas_resumen',
    userRole = 'seller',
    isSuperAdmin = false,
    embedded = false,
    activeSection = '',
    showNavigation = true,
    showHeader = true,
    closeLabel = 'Cerrar sesion',
    currentUser = null,
}) {
    const panelCoreState = useSaasPanelCoreState({
        activeSection,
        initialSection,
        EMPTY_TENANT_FORM,
        EMPTY_USER_FORM,
        EMPTY_CUSTOMER_FORM,
        EMPTY_SETTINGS,
        EMPTY_INTEGRATIONS_FORM,
        EMPTY_TENANT_CATALOG_FORM,
        EMPTY_CATALOG_PRODUCT_FORM,
        EMPTY_WA_MODULE_FORM,
        EMPTY_AI_ASSISTANT_FORM,
        EMPTY_ACCESS_CATALOG,
        EMPTY_ROLE_FORM,
        normalizePlanForm,
        EMPTY_QUICK_REPLY_LIBRARY_FORM,
        EMPTY_QUICK_REPLY_ITEM_FORM,
        EMPTY_LABEL_FORM
    });

    const {
        overview,
        setOverview,
        tenantForm,
        setTenantForm,
        userForm,
        setUserForm,
        settingsTenantId,
        setSettingsTenantId,
        tenantSettings,
        setTenantSettings,
        membershipDraft,
        setMembershipDraft,
        waModules,
        setWaModules,
        waModuleForm,
        setWaModuleForm,
        editingWaModuleId,
        setEditingWaModuleId,
        selectedTenantId,
        setSelectedTenantId,
        selectedUserId,
        setSelectedUserId,
        selectedWaModuleId,
        setSelectedWaModuleId,
        quickReplyModuleFilterId,
        setQuickReplyModuleFilterId,
        moduleQuickReplyLibraryDraft,
        setModuleQuickReplyLibraryDraft,
        selectedConfigKey,
        setSelectedConfigKey,
        moduleUserPickerId,
        setModuleUserPickerId,
        tenantPanelMode,
        setTenantPanelMode,
        userPanelMode,
        setUserPanelMode,
        tenantSettingsPanelMode,
        setTenantSettingsPanelMode,
        waModulePanelMode,
        setWaModulePanelMode,
        tenantIntegrations,
        setTenantIntegrations,
        tenantAiAssistants,
        setTenantAiAssistants,
        selectedAiAssistantId,
        setSelectedAiAssistantId,
        aiAssistantForm,
        setAiAssistantForm,
        aiAssistantPanelMode,
        setAiAssistantPanelMode,
        loadingAiAssistants,
        setLoadingAiAssistants,
        planMatrix,
        setPlanMatrix,
        selectedPlanId,
        setSelectedPlanId,
        planForm,
        setPlanForm,
        planPanelMode,
        setPlanPanelMode,
        accessCatalog,
        setAccessCatalog,
        loadingAccessCatalog,
        setLoadingAccessCatalog,
        selectedRoleKey,
        setSelectedRoleKey,
        roleForm,
        setRoleForm,
        rolePanelMode,
        setRolePanelMode,
        quickReplyLibraries,
        setQuickReplyLibraries,
        quickReplyItems,
        setQuickReplyItems,
        selectedQuickReplyLibraryId,
        setSelectedQuickReplyLibraryId,
        selectedQuickReplyItemId,
        setSelectedQuickReplyItemId,
        quickReplyLibraryForm,
        setQuickReplyLibraryForm,
        quickReplyItemForm,
        setQuickReplyItemForm,
        quickReplyLibraryPanelMode,
        setQuickReplyLibraryPanelMode,
        quickReplyItemPanelMode,
        setQuickReplyItemPanelMode,
        quickReplyLibrarySearch,
        setQuickReplyLibrarySearch,
        quickReplyItemSearch,
        setQuickReplyItemSearch,
        loadingQuickReplies,
        setLoadingQuickReplies,
        tenantLabels,
        setTenantLabels,
        selectedLabelId,
        setSelectedLabelId,
        labelForm,
        setLabelForm,
        labelPanelMode,
        setLabelPanelMode,
        labelSearch,
        setLabelSearch,
        loadingLabels,
        setLoadingLabels,
        customers,
        setCustomers,
        selectedCustomerId,
        setSelectedCustomerId,
        customerForm,
        setCustomerForm,
        customerPanelMode,
        setCustomerPanelMode,
        customerSearch,
        setCustomerSearch,
        customerCsvText,
        setCustomerCsvText,
        customerImportModuleId,
        setCustomerImportModuleId,
        busy,
        setBusy,
        loadingSettings,
        setLoadingSettings,
        loadingIntegrations,
        setLoadingIntegrations,
        loadingPlans,
        setLoadingPlans,
        error,
        setError,
        currentSection,
        setCurrentSection
    } = panelCoreState;
    const saasAccessControl = useSaasAccessControl({
        userRole,
        isSuperAdmin,
        currentUser,
        accessCatalog,
        selectedRoleKey,
        baseRoleOptions: BASE_ROLE_OPTIONS,
        getRolePriority,
        permissionKeys: {
            PERMISSION_OWNER_ASSIGN,
            PERMISSION_PLATFORM_OVERVIEW_READ,
            PERMISSION_PLATFORM_TENANTS_MANAGE,
            PERMISSION_PLATFORM_PLANS_MANAGE,
            PERMISSION_TENANT_USERS_MANAGE,
            PERMISSION_TENANT_SETTINGS_READ,
            PERMISSION_TENANT_SETTINGS_MANAGE,
            PERMISSION_TENANT_MODULES_READ,
            PERMISSION_TENANT_MODULES_MANAGE,
            PERMISSION_TENANT_QUICK_REPLIES_READ,
            PERMISSION_TENANT_QUICK_REPLIES_MANAGE,
            PERMISSION_TENANT_LABELS_READ,
            PERMISSION_TENANT_LABELS_MANAGE,
            PERMISSION_TENANT_AI_READ,
            PERMISSION_TENANT_AI_MANAGE,
            PERMISSION_TENANT_CUSTOMERS_READ,
            PERMISSION_TENANT_CUSTOMERS_MANAGE,
            PERMISSION_TENANT_CATALOGS_MANAGE,
            PERMISSION_TENANT_CHAT_ASSIGNMENTS_READ,
            PERMISSION_TENANT_CHAT_ASSIGNMENTS_MANAGE,
            PERMISSION_TENANT_KPIS_READ,
            PERMISSION_TENANT_INTEGRATIONS_READ,
            PERMISSION_TENANT_INTEGRATIONS_MANAGE
        }
    });

    const {
        normalizedRole,
        actorRoleForPolicy,
        actorRolePriority,
        currentUserId,
        canManageTenants,
        canManageUsers,
        canManageTenantSettings,
        canViewTenantSettings,
        canManageCatalog,
        canManageRoles,
        canViewSuperAdminSections,
        canEditTenantSettings,
        canEditModules,
        canViewModules,
        canManageQuickReplies,
        canViewQuickReplies,
        canManageLabels,
        canViewLabels,
        canViewAi,
        canManageAi,
        canViewCustomers,
        canManageCustomers,
        canViewOperations,
        canManageAssignments,
        canEditCatalog,
        requiresTenantSelection,
        canActorManageRoleChanges,
        roleOptions,
        canEditOptionalAccess,
        accessPackOptions,
        accessPackLabelMap,
        getOptionalPermissionKeysForRole,
        getAllowedPackIdsForRole,
        roleProfiles,
        roleLabelMap,
        selectedRoleProfile,
        permissionLabelMap,
        rolePermissionOptions,
        hasAccessCatalogData
    } = saasAccessControl;
    const { pendingRequests, requestJson } = useSaasApiClient({
        apiBase: API_BASE,
        buildApiHeaders
    });

    const operationsPanelState = useOperationsPanelState({
        canViewOperations,
        buildApiHeaders
    });
    const {
        assignmentRules,
        setAssignmentRules,
        loadingAssignmentRules,
        operationsKpis,
        loadingOperationsKpis,
        unassignedCandidates,
        operationsSnapshot,
        loadTenantAssignmentRules,
        loadTenantOperationsKpis,
        saveAssignmentRules,
        triggerAutoAssignPreview,
        resetOperationsState
    } = operationsPanelState;
    const panelLoadingState = useSaasPanelLoadingState({
        busy,
        error,
        overview,
        pendingRequests
    });
    const {
        showPanelLoading,
        aiUsageByTenant
    } = panelLoadingState;

    const {
        tenantScopeState,
        tenantDataLoaders,
        panelUserScopeState,
        panelDerivedData,
        tenantUsersState
    } = useSaasPanelDataContexts({
        overviewTenants: overview.tenants,
        overviewUsers: overview.users,
        selectedTenantId,
        settingsTenantId,
        requiresTenantSelection,
        activeTenantId,
        toTenantDisplayName,
        currentUser,
        actorRoleForPolicy,
        requestJson,
        setOverview,
        setSelectedTenantId,
        setSettingsTenantId,
        setSelectedUserId,
        setLoadingSettings,
        setTenantSettings,
        setLoadingIntegrations,
        setTenantIntegrations,
        setWaModules,
        setSelectedWaModuleId,
        setCustomers,
        setSelectedCustomerId,
        currentUserId,
        actorRolePriority,
        canManageUsers,
        canActorManageRoleChanges,
        canEditOptionalAccess,
        userPanelMode,
        userFormRole: userForm.role,
        canManageTenants,
        canManageCatalog,
        canManageLabels,
        canManageTenantSettings,
        canEditModules,
        canViewSuperAdminSections,
        resolvePrimaryRoleFromMemberships,
        sanitizeMemberships,
        getRolePriority,
        getOptionalPermissionKeysForRole,
        getAllowedPackIdsForRole,
        customerSearch,
        customers,
        waModules,
        selectedWaModuleId,
        quickReplyModuleFilterId,
        quickReplyLibraries,
        selectedQuickReplyLibraryId,
        quickReplyItems,
        selectedQuickReplyItemId,
        quickReplyItemForm,
        quickReplyLibrarySearch,
        quickReplyItemSearch,
        tenantLabels,
        selectedLabelId,
        labelSearch,
        planMatrix,
        quickReplyDefaultMaxUploadMb: QUICK_REPLY_DEFAULT_MAX_UPLOAD_MB,
        quickReplyDefaultStorageMb: QUICK_REPLY_DEFAULT_STORAGE_MB,
        selectedConfigKey,
        waModuleForm,
        tenantCatalogs: panelCoreState.tenantCatalogs,
        selectedCatalogId: panelCoreState.selectedCatalogId,
        tenantCatalogProducts: panelCoreState.tenantCatalogProducts,
        selectedCatalogProductId: panelCoreState.selectedCatalogProductId,
        tenantAiAssistants,
        selectedAiAssistantId,
        selectedPlanId,
        planOptions: PLAN_OPTIONS,
        toUserDisplayName
    });
    const {
        tenantOptions,
        selectedTenant,
        tenantScopeId,
        tenantScopeLocked,
        activeTenantLabel,
        currentUserDisplayName,
        currentUserEmail,
        currentUserAvatarUrl,
        currentUserRole,
        currentUserRoleLabel,
        currentUserTenantCount
    } = tenantScopeState;
    const {
        refreshOverview,
        loadTenantSettings,
        loadTenantIntegrations,
        loadWaModules,
        loadCustomers
    } = tenantDataLoaders;
    const {
        currentUserCapabilities,
        scopedUsers,
        selectedUser,
        selectedUserRole,
        selectedUserRolePriority,
        selectedUserIsSelf,
        canEditSelectedUser,
        canEditSelectedUserRole,
        canToggleSelectedUserStatus,
        canEditSelectedUserOptionalAccess,
        canEditRoleInUserForm,
        canEditScopeInUserForm,
        canConfigureOptionalAccessInUserForm,
        allowedOptionalPermissionsForUserFormRole,
        allowedPackIdsForUserFormRole
    } = panelUserScopeState;
    const {
        filteredCustomers,
        selectedCustomer,
        selectedWaModule,
        quickReplyScopeModuleId,
        quickReplyLibrariesByScope,
        selectedQuickReplyLibrary,
        quickReplyItemsForSelectedLibrary,
        selectedQuickReplyItem,
        selectedQuickReplyItemMediaAssets,
        quickReplyItemFormAssets,
        visibleQuickReplyLibraries,
        visibleQuickReplyItemsForSelectedLibrary,
        tenantLabelItems,
        selectedTenantLabel,
        visibleTenantLabels,
        selectedSettingsTenant,
        quickReplyTenantPlanId,
        quickReplyUploadMaxMb,
        quickReplyStorageQuotaMb,
        quickReplyUploadMaxBytes,
        selectedConfigModule,
        activeQuickReplyLibraries,
        moduleQuickReplySourceModuleId,
        moduleQuickReplyAssignedLibraries,
        moduleQuickReplyAssignedLibraryIds,
        tenantAiAssistantItems,
        activeAiAssistantOptions,
        selectedAiAssistant,
        defaultAiAssistantId,
        aiAssistantLabelMap,
        planIds,
        selectedPlan
    } = panelDerivedData;
    const {
        usersByTenant,
        usersForSettingsTenant,
        assignedModuleUsers,
        availableUsersForModulePicker
    } = tenantUsersState;
    const {
        catalogState,
        catalogDerived
    } = useSaasCatalogController({
        panelCoreState,
        panelDerivedData
    });
    const scrollToSection = (sectionId, behavior = 'smooth') => {
        const cleanSection = String(sectionId || '').trim();
        if (!cleanSection) return;
        const node = document.getElementById(cleanSection);
        if (node && typeof node.scrollIntoView === 'function') {
            node.scrollIntoView({ behavior, block: 'start' });
        }
    };
    const {
        quickReplyAssetsUploadState,
        quickReplyAdminActions,
        tenantLabelsAdminActions,
        catalogAdminActions,
        aiAssistantsAdminActions,
        plansRolesActions,
        tenantsUsersActions,
        customersAdminActions,
        panelNavigation,
        assignmentRoleOptions,
        operationAccess,
        moduleSectionActions,
        lifecycleState
    } = useSaasPanelActionContexts({
        requestJson,
        settingsTenantId,
        selectedQuickReplyLibrary,
        quickReplyUploadMaxBytes,
        quickReplyUploadMaxMb,
        setQuickReplyItemForm,
        waModules,
        selectedQuickReplyLibraryId,
        selectedQuickReplyItem,
        selectedQuickReplyItemId,
        quickReplyScopeModuleId,
        quickReplyLibraryForm,
        quickReplyItemForm,
        quickReplyLibraryPanelMode,
        quickReplyItemPanelMode,
        emptyQuickReplyLibraryForm: EMPTY_QUICK_REPLY_LIBRARY_FORM,
        emptyQuickReplyItemForm: EMPTY_QUICK_REPLY_ITEM_FORM,
        setQuickReplyLibraries,
        setQuickReplyItems,
        setSelectedQuickReplyLibraryId,
        setSelectedQuickReplyItemId,
        setQuickReplyModuleFilterId,
        setQuickReplyLibraryForm,
        setQuickReplyLibraryPanelMode,
        setQuickReplyItemPanelMode,
        setLoadingQuickReplies,
        selectedTenantLabel,
        selectedLabelId,
        labelForm,
        labelPanelMode,
        emptyLabelForm: EMPTY_LABEL_FORM,
        defaultLabelColors: DEFAULT_LABEL_COLORS,
        setTenantLabels,
        setLabelForm,
        setLabelPanelMode,
        setLoadingLabels,
        canEditCatalog,
        selectedTenantCatalog: catalogDerived.selectedTenantCatalog,
        selectedCatalogProduct: catalogDerived.selectedCatalogProduct,
        selectedCatalogProductId: catalogState.selectedCatalogProductId,
        catalogProductForm: catalogState.catalogProductForm,
        catalogProductPanelMode: catalogState.catalogProductPanelMode,
        emptyCatalogProductForm: EMPTY_CATALOG_PRODUCT_FORM,
        emptyTenantCatalogForm: EMPTY_TENANT_CATALOG_FORM,
        setTenantCatalogs: catalogState.setTenantCatalogs,
        setSelectedCatalogId: catalogState.setSelectedCatalogId,
        setTenantCatalogForm: catalogState.setTenantCatalogForm,
        setTenantCatalogProducts: catalogState.setTenantCatalogProducts,
        setCatalogProductForm: catalogState.setCatalogProductForm,
        setCatalogProductPanelMode: catalogState.setCatalogProductPanelMode,
        setCatalogProductImageError: catalogState.setCatalogProductImageError,
        setCatalogProductImageUploading: catalogState.setCatalogProductImageUploading,
        setLoadingTenantCatalogs: catalogState.setLoadingTenantCatalogs,
        setLoadingCatalogProducts: catalogState.setLoadingCatalogProducts,
        setCatalogPanelMode: catalogState.setCatalogPanelMode,
        canManageAi,
        selectedAiAssistant,
        selectedAiAssistantId,
        aiAssistantForm,
        aiAssistantPanelMode,
        tenantIntegrations,
        emptyAiAssistantForm: EMPTY_AI_ASSISTANT_FORM,
        setLoadingAiAssistants,
        setTenantAiAssistants,
        setAiAssistantForm,
        canManageRoles,
        selectedRoleProfile,
        selectedRoleKey,
        roleForm,
        rolePanelMode,
        selectedPlanId,
        planMatrix,
        planOptions: PLAN_OPTIONS,
        emptyRoleForm: EMPTY_ROLE_FORM,
        setLoadingPlans,
        setPlanMatrix,
        setPlanForm,
        setPlanPanelMode,
        setRolePanelMode,
        setLoadingAccessCatalog,
        setAccessCatalog,
        setRoleForm,
        loadingAccessCatalog,
        accessCatalog,
        canEditSelectedUser,
        selectedTenant,
        selectedUser,
        tenantScopeId,
        selectedTenantId,
        tenantOptions,
        roleOptions,
        emptyTenantForm: EMPTY_TENANT_FORM,
        emptyUserForm: EMPTY_USER_FORM,
        setTenantPanelMode,
        setSettingsTenantId,
        setTenantForm,
        setUserPanelMode,
        setSelectedUserId,
        setMembershipDraft,
        setUserForm,
        customerImportModuleId,
        emptyCustomerForm: EMPTY_CUSTOMER_FORM,
        setCustomerPanelMode,
        setCustomerForm,
        navItems: ADMIN_NAV_ITEMS,
        currentSection,
        activeSection,
        initialSection,
        canManageTenants,
        canManageUsers,
        canViewCustomers,
        canViewOperations,
        canViewAi,
        canViewLabels,
        canViewQuickReplies,
        canViewModules,
        canManageCatalog,
        canViewSuperAdminSections,
        canViewTenantSettings,
        requiresTenantSelection,
        activeTenantId,
        onOpenWhatsAppOperation,
        canEditTenantSettings,
        canEditModules,
        selectedConfigModule,
        activeCatalogOptions: catalogDerived.activeCatalogOptions,
        defaultAiAssistantId,
        setSelectedConfigKey,
        setSelectedRoleKey,
        setSelectedWaModuleId,
        setTenantSettingsPanelMode,
        setWaModulePanelMode,
        setModuleUserPickerId,
        setModuleQuickReplyLibraryDraft,
        emptyWaModuleForm: EMPTY_WA_MODULE_FORM,
        emptyIntegrationsForm: EMPTY_INTEGRATIONS_FORM,
        normalizePlanForm,
        setWaModuleForm,
        setSelectedCustomerId,
        setCustomerSearch,
        setCustomerCsvText,
        setCustomerImportModuleId,
        setSelectedAiAssistantId,
        setCurrentSection,
        isOpen,
        canManageSaas,
        setError,
        setBusy,
        refreshOverview,
        loadTenantSettings,
        loadWaModules,
        loadTenantIntegrations,
        loadCustomers,
        loadTenantAssignmentRules,
        loadTenantOperationsKpis,
        selectedWaModuleId,
        selectedConfigKey,
        selectedCatalogId: catalogState.selectedCatalogId,
        tenantSettingsPanelMode,
        waModulePanelMode,
        catalogPanelMode: catalogState.catalogPanelMode,
        planPanelMode,
        customerPanelMode,
        labelSearch,
        launchSource,
        preferredTenantId,
        resetOperationsState,
        setLabelSearch,
        catalogProductImageError: catalogState.catalogProductImageError,
        editingWaModuleId,
        buildTenantFormFromItem,
        buildUserFormFromItem,
        normalizeCustomerFormFromItem,
        buildAiAssistantFormFromItem,
        buildTenantCatalogFormFromItem,
        normalizeQuickReplyMediaAssets,
        scrollToSection
    });
    const {
        runAction,
        handleOpenOperation,
        handleFormImageUpload,
        openTenantFromUserMembership,
        openUserFromTenant
    } = lifecycleState;
    const {
        selectedSectionId,
        sharedHeaderProps,
        frameProps
    } = useSaasFrameNavigationController({
        panelNavigation,
        operationAccess,
        moduleSectionActions,
        lifecycleState,
        onLogout,
        onClose,
        setSettingsTenantId,
        setSelectedTenantId,
        embedded,
        showHeader,
        busy,
        currentUserAvatarUrl,
        currentUserDisplayName,
        currentUserRoleLabel,
        buildInitials,
        closeLabel,
        activeTenantLabel,
        error,
        showPanelLoading,
        requiresTenantSelection,
        settingsTenantId,
        tenantOptions,
        toTenantDisplayName,
        showNavigation,
        tenantScopeLocked
    });

    const sectionContextsInput = {
        panelCoreState,
        saasAccessControl,
        operationsPanelState,
        panelLoadingState,
        tenantScopeState,
        tenantDataLoaders,
        panelUserScopeState,
        panelDerivedData,
        tenantUsersState,
        quickReplyAssetsUploadState,
        quickReplyAdminActions,
        tenantLabelsAdminActions,
        catalogAdminActions,
        aiAssistantsAdminActions,
        plansRolesActions,
        tenantsUsersActions,
        customersAdminActions,
        panelNavigation,
        operationAccess,
        moduleSectionActions,
        lifecycleState,
        extras: buildPanelSectionExtras({
            selectedSectionId,
            requestJson,
            runAction,
            activeTenantId,
            assignmentRoleOptions,
            handleOpenOperation,
            handleFormImageUpload,
            openTenantFromUserMembership,
            openUserFromTenant,
            buildInitials,
            toTenantDisplayName,
            toUserDisplayName,
            formatDateTimeLabel,
            normalizeCatalogIdsList,
            sanitizeAiAssistantCode,
            normalizeQuickReplyMediaAssets,
            resolveQuickReplyAssetPreviewUrl,
            isQuickReplyImageAsset,
            getQuickReplyAssetTypeLabel,
            getQuickReplyAssetDisplayName,
            formatBytes,
            chunkItems,
            PLAN_OPTIONS,
            AI_MODEL_OPTIONS,
            EMPTY_AI_ASSISTANT_FORM,
            DEFAULT_LABEL_COLORS,
            QUICK_REPLY_ALLOWED_EXTENSIONS_LABEL,
            QUICK_REPLY_ACCEPT_VALUE,
            MODULE_KEYS,
            CATALOG_MODE_OPTIONS,
            EMPTY_TENANT_CATALOG_FORM,
            buildTenantCatalogPayload,
            buildCatalogProductFormFromItem,
            PLAN_LIMIT_KEYS,
            PLAN_FEATURE_KEYS,
            sanitizeRoleCode,
            buildCustomerPayloadFromForm
        })
    };

    const {
        entitySectionsContext,
        opsAndAutomationSectionsContext,
        configAndGovernanceSectionsContext
    } = useSaasPanelSectionContexts(sectionContextsInput);

    return {
        isOpen,
        canManageSaas,
        selectedSectionId,
        sharedHeaderProps,
        frameProps,
        entitySectionsContext,
        opsAndAutomationSectionsContext,
        configAndGovernanceSectionsContext
    };
}





