function registerHttpRoutes({
    app,
    hasOpsAccess,
    waClient,
    opsTelemetry,
    tenantService,
    authService,
    opsReadyRequireWa,
    registerOperationsHealthHttpRoutes,
    registerTenantRuntimePublicHttpRoutes,
    registerSecurityAuthHttpRoutes,
    registerSecurityAccessControlHttpRoutes,
    registerTenantAssetsUploadHttpRoutes,
    registerTenantAdminTenantsUsersHttpRoutes,
    registerTenantWaModuleAdminHttpRoutes,
    registerTenantCustomerHttpRoutes,
    registerOperationsHttpRoutes,
    registerTenantRuntimeSettingsHttpRoutes,
    registerTenantLabelsQuickRepliesHttpRoutes,
    registerTenantAdminConfigCatalogHttpRoutes,
    registerOperationsUtilityHttpRoutes,
    registerCloudWebhookHttpRoutes,
    isProduction,
    authRecoveryService,
    auditLogService,
    toPublicTenant,
    saasControlService,
    aiUsageService,
    accessPolicyService,
    planLimitsService,
    planLimitsStoreService,
    hasSaasControlReadAccess,
    hasSaasControlWriteAccess,
    getAuthRole,
    filterAdminOverviewByScope,
    sanitizeObjectPayload,
    tenantLabelService,
    tenantZoneRulesService,
    saasUserUiPreferencesService,
    quickReplyLibrariesService,
    customerService,
    customerAddressesService,
    customerCatalogsService,
    waModuleService,
    hasPermission,
    hasAnyPermission,
    isTenantAllowedForUser,
    normalizeAssetUploadKind,
    sanitizeStorageSegment,
    resolveTenantQuickReplyAssetLimits,
    parseAssetUploadPayload,
    adminAssetQuickReplyMaxBytes,
    estimateDirectorySizeBytes,
    uploadsRoot,
    path,
    saveAssetFile,
    getRequestOrigin,
    saasSocketAuthRequired,
    hasTenantAdminWriteAccess,
    hasTenantModuleReadAccess,
    sanitizeTenantPayload,
    sanitizeUserPayload,
    sanitizeMembershipPayload,
    resolvePrimaryRoleFromMemberships,
    canActorAssignRole,
    hasAnyAccessOverride,
    canActorEditOptionalAccess,
    getUserPrimaryRole,
    isSelfUserAction,
    isActorSuperiorToRole,
    canActorManageRoleChanges,
    sanitizeWaModulePayload,
    invalidateWebhookCloudRegistryCache,
    hasTenantModuleWriteAccess,
    conversationOpsService,
    customerConsentService,
    customerModuleContextsService,
    templateWebhookEventsService,
    templateVariablesService,
    campaignsService,
    chatCommercialStatusService,
    metaTemplatesService,
    chatAssignmentPolicyService,
    assignmentRulesService,
    chatAssignmentRouterService,
    operationsKpiService,
    globalLabelsService,
    normalizeScopeModuleId,
    hasConversationEventsReadAccess,
    hasChatAssignmentsReadAccess,
    hasChatAssignmentsWriteAccess,
    hasAssignmentRulesReadAccess,
    hasAssignmentRulesWriteAccess,
    hasOperationsKpiReadAccess,
    tenantSettingsService,
    tenantIntegrationsService,
    tenantCatalogService,
    sanitizeAiAssistantIdPayload,
    sanitizeAiAssistantPayload,
    loadCatalog,
    addProduct,
    updateProduct,
    messageHistoryService,
    parseCsvEnv,
    resolveAndValidatePublicHost,
    logger,
    socketManager,
    sanitizeTenantLabelPayload,
    sanitizeQuickReplyLibraryPayload,
    sanitizeQuickReplyItemPayload
}) {
    registerOperationsHealthHttpRoutes({
        app,
        hasOpsAccess,
        waClient,
        opsTelemetry,
        tenantService,
        authService,
        opsReadyRequireWa
    });

    registerTenantRuntimePublicHttpRoutes({
        app,
        authService,
        tenantService,
        tenantSettingsService,
        waModuleService,
        saasSocketAuthRequired
    });

    registerSecurityAuthHttpRoutes({
        app,
        isProduction,
        authService,
        authRecoveryService,
        auditLogService,
        tenantService,
        toPublicTenant
    });

    registerSecurityAccessControlHttpRoutes({
        app,
        saasControlService,
        aiUsageService,
        accessPolicyService,
        planLimitsService,
        planLimitsStoreService,
        hasSaasControlReadAccess,
        hasSaasControlWriteAccess,
        getAuthRole,
        filterAdminOverviewByScope,
        sanitizeObjectPayload
    });

    registerTenantAssetsUploadHttpRoutes({
        app,
        accessPolicyService,
        hasPermission,
        isTenantAllowedForUser,
        normalizeAssetUploadKind,
        sanitizeStorageSegment,
        resolveTenantQuickReplyAssetLimits,
        parseAssetUploadPayload,
        adminAssetQuickReplyMaxBytes,
        estimateDirectorySizeBytes,
        uploadsRoot,
        path,
        saveAssetFile,
        getRequestOrigin
    });

    registerTenantAdminTenantsUsersHttpRoutes({
        app,
        saasControlService,
        waModuleService,
        hasSaasControlReadAccess,
        hasSaasControlWriteAccess,
        hasTenantAdminWriteAccess,
        hasTenantModuleReadAccess,
        isTenantAllowedForUser,
        sanitizeTenantPayload,
        sanitizeUserPayload,
        sanitizeMembershipPayload,
        resolvePrimaryRoleFromMemberships,
        canActorAssignRole,
        hasAnyAccessOverride,
        canActorEditOptionalAccess,
        getUserPrimaryRole,
        isSelfUserAction,
        isActorSuperiorToRole,
        canActorManageRoleChanges
    });

    registerTenantWaModuleAdminHttpRoutes({
        app,
        waModuleService,
        sanitizeWaModulePayload,
        invalidateWebhookCloudRegistryCache,
        hasTenantModuleWriteAccess
    });

    registerTenantCustomerHttpRoutes({
        app,
        authService,
        accessPolicyService,
        customerService,
        customerAddressesService,
        customerCatalogsService,
        tenantZoneRulesService,
        waModuleService,
        isTenantAllowedForUser,
        hasPermission
    });

    registerOperationsHttpRoutes({
        app,
        authService,
        auditLogService,
        customerService,
        customerConsentService,
        customerModuleContextsService,
        templateWebhookEventsService,
        templateVariablesService,
        campaignsService,
        conversationOpsService,
        chatCommercialStatusService,
        metaTemplatesService,
        chatAssignmentPolicyService,
        assignmentRulesService,
        chatAssignmentRouterService,
        operationsKpiService,
        globalLabelsService,
        normalizeScopeModuleId,
        hasConversationEventsReadAccess,
        hasChatAssignmentsReadAccess,
        hasChatAssignmentsWriteAccess,
        hasAssignmentRulesReadAccess,
        hasAssignmentRulesWriteAccess,
        hasOperationsKpiReadAccess,
        emitCommercialStatusUpdated: socketManager?.emitCommercialStatusUpdated?.bind(socketManager) || null
    });

    registerTenantRuntimeSettingsHttpRoutes({
        app,
        authService,
        tenantService,
        tenantSettingsService,
        auditLogService,
        aiUsageService,
        waClient,
        accessPolicyService,
        isTenantAllowedForUser,
        hasPermission
    });

    registerTenantLabelsQuickRepliesHttpRoutes({
        app,
        accessPolicyService,
        tenantLabelService,
        saasUserUiPreferencesService,
        quickReplyLibrariesService,
        isTenantAllowedForUser,
        hasAnyPermission,
        sanitizeTenantLabelPayload,
        sanitizeQuickReplyLibraryPayload,
        sanitizeQuickReplyItemPayload
    });

    registerTenantAdminConfigCatalogHttpRoutes({
        app,
        tenantService,
        tenantSettingsService,
        tenantIntegrationsService,
        tenantCatalogService,
        planLimitsService,
        accessPolicyService,
        isTenantAllowedForUser,
        hasPermission,
        hasAnyPermission,
        sanitizeAiAssistantIdPayload,
        sanitizeAiAssistantPayload,
        loadCatalog,
        addProduct,
        updateProduct
    });

    registerOperationsUtilityHttpRoutes({
        app,
        authService,
        tenantService,
        messageHistoryService,
        auditLogService,
        waClient,
        parseCsvEnv,
        resolveAndValidatePublicHost
    });

    registerCloudWebhookHttpRoutes({
        app,
        logger,
        saasControlService,
        waModuleService,
        waClient,
        socketManager
    });
}

module.exports = {
    registerHttpRoutes
};
