import { useCallback, useEffect, useMemo } from 'react';

import * as saasAdminPanelHelpers from '../helpers';
import {
    SaasPanelConfigAndGovernanceSections,
    SaasPanelEntitySections,
    SaasPanelFrame,
    SaasPanelNoAccess,
    SaasPanelOpsAndAutomationSections
} from './panel';
import {
    useAiAssistantsAdminActions,
    useCatalogAdminActions,
    useCustomersAdminActions,
    useOperationsPanelState,
    usePlansRolesAdminActions,
    useQuickReplyAdminActions,
    useQuickReplyAssetsUpload,
    useSaasAccessControl,
    useSaasApiClient,
    useSaasModuleSectionActions,
    useSaasOperationAccess,
    useSaasPanelCoreState,
    useSaasPanelDerivedData,
    useSaasPanelLifecycle,
    useSaasPanelLoadingState,
    useSaasPanelNavigation,
    useSaasPanelUserScopeState,
    useSaasRunActionBridge,
    useSaasTenantDataLoaders,
    useSaasTenantScope,
    useSaasTenantUsers,
    useTenantLabelsActions,
    useTenantsUsersAdminActions
} from '../hooks';
const {
    API_BASE,
    EMPTY_TENANT_FORM,
    EMPTY_USER_FORM,
    EMPTY_CUSTOMER_FORM,
    EMPTY_SETTINGS,
    EMPTY_INTEGRATIONS_FORM,
    EMPTY_TENANT_CATALOG_FORM,
    EMPTY_CATALOG_PRODUCT_FORM,
    buildCatalogProductFormFromItem,
    normalizeCatalogIdsList,
    buildTenantCatalogFormFromItem,
    buildTenantCatalogPayload,
    EMPTY_ACCESS_CATALOG,
    EMPTY_ROLE_FORM,
    PLAN_LIMIT_KEYS,
    PLAN_FEATURE_KEYS,
    EMPTY_WA_MODULE_FORM,
    EMPTY_AI_ASSISTANT_FORM,
    BASE_ROLE_OPTIONS,
    PLAN_OPTIONS,
    CATALOG_MODE_OPTIONS,
    MODULE_KEYS,
    ADMIN_NAV_ITEMS,
    AI_PROVIDER_OPTIONS,
    AI_MODEL_OPTIONS,
    LAVITAT_FIRST_ASSISTANT_SYSTEM_PROMPT,
    ROLE_PRIORITY,
    PERMISSION_OWNER_ASSIGN,
    PERMISSION_PLATFORM_OVERVIEW_READ,
    PERMISSION_PLATFORM_TENANTS_MANAGE,
    PERMISSION_PLATFORM_PLANS_MANAGE,
    PERMISSION_TENANT_OVERVIEW_READ,
    PERMISSION_TENANT_USERS_MANAGE,
    PERMISSION_TENANT_SETTINGS_READ,
    PERMISSION_TENANT_SETTINGS_MANAGE,
    PERMISSION_TENANT_INTEGRATIONS_READ,
    PERMISSION_TENANT_INTEGRATIONS_MANAGE,
    PERMISSION_TENANT_MODULES_READ,
    PERMISSION_TENANT_MODULES_MANAGE,
    PERMISSION_TENANT_QUICK_REPLIES_READ,
    PERMISSION_TENANT_QUICK_REPLIES_MANAGE,
    PERMISSION_TENANT_LABELS_READ,
    PERMISSION_TENANT_LABELS_MANAGE,
    PERMISSION_TENANT_AI_READ,
    PERMISSION_TENANT_AI_MANAGE,
    PERMISSION_TENANT_CUSTOMERS_READ,
    PERMISSION_TENANT_CUSTOMERS_MANAGE,
    PERMISSION_TENANT_CATALOGS_MANAGE,
    PERMISSION_TENANT_CHAT_ASSIGNMENTS_READ,
    PERMISSION_TENANT_CHAT_ASSIGNMENTS_MANAGE,
    PERMISSION_TENANT_KPIS_READ,
    QUICK_REPLY_ALLOWED_EXTENSIONS,
    QUICK_REPLY_ALLOWED_EXTENSIONS_LABEL,
    QUICK_REPLY_ACCEPT_VALUE,
    QUICK_REPLY_DEFAULT_MAX_UPLOAD_MB,
    QUICK_REPLY_DEFAULT_STORAGE_MB,
    EMPTY_QUICK_REPLY_LIBRARY_FORM,
    EMPTY_QUICK_REPLY_ITEM_FORM,
    DEFAULT_LABEL_COLORS,
    EMPTY_LABEL_FORM,
    normalizeQuickReplyMediaAsset,
    normalizeQuickReplyMediaAssets,
    resolveQuickReplyAssetPreviewUrl,
    isQuickReplyImageAsset,
    getQuickReplyAssetTypeLabel,
    getQuickReplyAssetDisplayName,
    normalizeTenantLabelColor,
    buildTenantLabelPayload,
    sanitizeMemberships,
    resolvePrimaryRoleFromMemberships,
    getRolePriority,
    sanitizeAiAssistantCode,
    buildAiAssistantFormFromItem,
    buildIntegrationsUpdatePayload,
    normalizePlanForm,
    sanitizeRoleCode,
    buildTenantFormFromItem,
    buildUserFormFromItem,
    normalizeCustomerFormFromItem,
    buildCustomerPayloadFromForm,
    formatDateTimeLabel,
    toTenantDisplayName,
    toUserDisplayName,
    buildInitials,
    formatBytes,
    chunkItems
} = saasAdminPanelHelpers;

export default function SaasAdminPanel({
    isOpen = false,
    onClose,
    onLogout,
    onOpenWhatsAppOperation,
    buildApiHeaders,
    activeTenantId = '',
    preferredTenantId = '',
    launchSource = '',
    canManageSaas = false,
    initialSection = 'saas_resumen',
    userRole = 'seller',
    isSuperAdmin = false,
    embedded = false,
    activeSection = '',
    showNavigation = true,
    showHeader = true,
    closeLabel = 'Cerrar sesion',
    currentUser = null,
}) {    const {
        overview,
        setOverview,
        tenantForm,
        setTenantForm,
        userForm,
        setUserForm,
        settingsTenantId,
        setSettingsTenantId,
        tenantSettings,
        setTenantSettings,
        membershipDraft,
        setMembershipDraft,
        waModules,
        setWaModules,
        waModuleForm,
        setWaModuleForm,
        editingWaModuleId,
        setEditingWaModuleId,
        selectedTenantId,
        setSelectedTenantId,
        selectedUserId,
        setSelectedUserId,
        selectedWaModuleId,
        setSelectedWaModuleId,
        quickReplyModuleFilterId,
        setQuickReplyModuleFilterId,
        moduleQuickReplyLibraryDraft,
        setModuleQuickReplyLibraryDraft,
        selectedConfigKey,
        setSelectedConfigKey,
        moduleUserPickerId,
        setModuleUserPickerId,
        tenantPanelMode,
        setTenantPanelMode,
        userPanelMode,
        setUserPanelMode,
        tenantSettingsPanelMode,
        setTenantSettingsPanelMode,
        waModulePanelMode,
        setWaModulePanelMode,
        tenantIntegrations,
        setTenantIntegrations,
        tenantCatalogs,
        setTenantCatalogs,
        selectedCatalogId,
        setSelectedCatalogId,
        tenantCatalogForm,
        setTenantCatalogForm,
        loadingTenantCatalogs,
        setLoadingTenantCatalogs,
        catalogPanelMode,
        setCatalogPanelMode,
        tenantCatalogProducts,
        setTenantCatalogProducts,
        selectedCatalogProductId,
        setSelectedCatalogProductId,
        catalogProductForm,
        setCatalogProductForm,
        catalogProductPanelMode,
        setCatalogProductPanelMode,
        loadingCatalogProducts,
        setLoadingCatalogProducts,
        catalogProductImageUploading,
        setCatalogProductImageUploading,
        catalogProductImageError,
        setCatalogProductImageError,
        tenantAiAssistants,
        setTenantAiAssistants,
        selectedAiAssistantId,
        setSelectedAiAssistantId,
        aiAssistantForm,
        setAiAssistantForm,
        aiAssistantPanelMode,
        setAiAssistantPanelMode,
        loadingAiAssistants,
        setLoadingAiAssistants,
        planMatrix,
        setPlanMatrix,
        selectedPlanId,
        setSelectedPlanId,
        planForm,
        setPlanForm,
        planPanelMode,
        setPlanPanelMode,
        accessCatalog,
        setAccessCatalog,
        loadingAccessCatalog,
        setLoadingAccessCatalog,
        selectedRoleKey,
        setSelectedRoleKey,
        roleForm,
        setRoleForm,
        rolePanelMode,
        setRolePanelMode,
        quickReplyLibraries,
        setQuickReplyLibraries,
        quickReplyItems,
        setQuickReplyItems,
        selectedQuickReplyLibraryId,
        setSelectedQuickReplyLibraryId,
        selectedQuickReplyItemId,
        setSelectedQuickReplyItemId,
        quickReplyLibraryForm,
        setQuickReplyLibraryForm,
        quickReplyItemForm,
        setQuickReplyItemForm,
        quickReplyLibraryPanelMode,
        setQuickReplyLibraryPanelMode,
        quickReplyItemPanelMode,
        setQuickReplyItemPanelMode,
        quickReplyLibrarySearch,
        setQuickReplyLibrarySearch,
        quickReplyItemSearch,
        setQuickReplyItemSearch,
        loadingQuickReplies,
        setLoadingQuickReplies,
        tenantLabels,
        setTenantLabels,
        selectedLabelId,
        setSelectedLabelId,
        labelForm,
        setLabelForm,
        labelPanelMode,
        setLabelPanelMode,
        labelSearch,
        setLabelSearch,
        loadingLabels,
        setLoadingLabels,
        customers,
        setCustomers,
        selectedCustomerId,
        setSelectedCustomerId,
        customerForm,
        setCustomerForm,
        customerPanelMode,
        setCustomerPanelMode,
        customerSearch,
        setCustomerSearch,
        customerCsvText,
        setCustomerCsvText,
        customerImportModuleId,
        setCustomerImportModuleId,
        busy,
        setBusy,
        loadingSettings,
        setLoadingSettings,
        loadingIntegrations,
        setLoadingIntegrations,
        loadingPlans,
        setLoadingPlans,
        error,
        setError,
        currentSection,
        setCurrentSection
    } = useSaasPanelCoreState({
        activeSection,
        initialSection,
        EMPTY_TENANT_FORM,
        EMPTY_USER_FORM,
        EMPTY_CUSTOMER_FORM,
        EMPTY_SETTINGS,
        EMPTY_INTEGRATIONS_FORM,
        EMPTY_TENANT_CATALOG_FORM,
        EMPTY_CATALOG_PRODUCT_FORM,
        EMPTY_WA_MODULE_FORM,
        EMPTY_AI_ASSISTANT_FORM,
        EMPTY_ACCESS_CATALOG,
        EMPTY_ROLE_FORM,
        normalizePlanForm,
        EMPTY_QUICK_REPLY_LIBRARY_FORM,
        EMPTY_QUICK_REPLY_ITEM_FORM,
        EMPTY_LABEL_FORM
    });

    const {
        normalizedRole,
        actorRoleForPolicy,
        actorRolePriority,
        currentUserId,
        canManageTenants,
        canManageUsers,
        canManageTenantSettings,
        canViewTenantSettings,
        canManageCatalog,
        canManageRoles,
        canViewSuperAdminSections,
        canEditTenantSettings,
        canEditModules,
        canViewModules,
        canManageQuickReplies,
        canViewQuickReplies,
        canManageLabels,
        canViewLabels,
        canViewAi,
        canManageAi,
        canViewCustomers,
        canManageCustomers,
        canViewOperations,
        canManageAssignments,
        canEditCatalog,
        requiresTenantSelection,
        canActorManageRoleChanges,
        roleOptions,
        canEditOptionalAccess,
        accessPackOptions,
        accessPackLabelMap,
        getOptionalPermissionKeysForRole,
        getAllowedPackIdsForRole,
        roleProfiles,
        roleLabelMap,
        selectedRoleProfile,
        permissionLabelMap,
        rolePermissionOptions,
        hasAccessCatalogData
    } = useSaasAccessControl({
        userRole,
        isSuperAdmin,
        currentUser,
        accessCatalog,
        selectedRoleKey,
        baseRoleOptions: BASE_ROLE_OPTIONS,
        getRolePriority,
        permissionKeys: {
            PERMISSION_OWNER_ASSIGN,
            PERMISSION_PLATFORM_OVERVIEW_READ,
            PERMISSION_PLATFORM_TENANTS_MANAGE,
            PERMISSION_PLATFORM_PLANS_MANAGE,
            PERMISSION_TENANT_USERS_MANAGE,
            PERMISSION_TENANT_SETTINGS_READ,
            PERMISSION_TENANT_SETTINGS_MANAGE,
            PERMISSION_TENANT_MODULES_READ,
            PERMISSION_TENANT_MODULES_MANAGE,
            PERMISSION_TENANT_QUICK_REPLIES_READ,
            PERMISSION_TENANT_QUICK_REPLIES_MANAGE,
            PERMISSION_TENANT_LABELS_READ,
            PERMISSION_TENANT_LABELS_MANAGE,
            PERMISSION_TENANT_AI_READ,
            PERMISSION_TENANT_AI_MANAGE,
            PERMISSION_TENANT_CUSTOMERS_READ,
            PERMISSION_TENANT_CUSTOMERS_MANAGE,
            PERMISSION_TENANT_CATALOGS_MANAGE,
            PERMISSION_TENANT_CHAT_ASSIGNMENTS_READ,
            PERMISSION_TENANT_CHAT_ASSIGNMENTS_MANAGE,
            PERMISSION_TENANT_KPIS_READ,
            PERMISSION_TENANT_INTEGRATIONS_READ,
            PERMISSION_TENANT_INTEGRATIONS_MANAGE
        }
    });
    const { pendingRequests, requestJson } = useSaasApiClient({
        apiBase: API_BASE,
        buildApiHeaders
    });

    const {
        assignmentRules,
        setAssignmentRules,
        loadingAssignmentRules,
        operationsKpis,
        loadingOperationsKpis,
        unassignedCandidates,
        operationsSnapshot,
        loadTenantAssignmentRules,
        loadTenantOperationsKpis,
        saveAssignmentRules,
        triggerAutoAssignPreview,
        resetOperationsState
    } = useOperationsPanelState({
        canViewOperations,
        buildApiHeaders
    });
    const {
        showPanelLoading,
        aiUsageByTenant
    } = useSaasPanelLoadingState({
        busy,
        error,
        overview,
        pendingRequests
    });


    const {
        tenantOptions,
        selectedTenant,
        tenantScopeId,
        tenantScopeLocked,
        activeTenantLabel,
        currentUserDisplayName,
        currentUserEmail,
        currentUserAvatarUrl,
        currentUserRole,
        currentUserRoleLabel,
        currentUserTenantCount
    } = useSaasTenantScope({
        overviewTenants: overview.tenants,
        selectedTenantId,
        settingsTenantId,
        requiresTenantSelection,
        activeTenantId,
        toTenantDisplayName,
        currentUser,
        actorRoleForPolicy
    });

    const {
        refreshOverview,
        loadTenantSettings,
        loadTenantIntegrations,
        loadWaModules,
        loadCustomers
    } = useSaasTenantDataLoaders({
        requestJson,
        requiresTenantSelection,
        activeTenantId,
        setOverview,
        setSelectedTenantId,
        setSettingsTenantId,
        setSelectedUserId,
        setLoadingSettings,
        setTenantSettings,
        setLoadingIntegrations,
        setTenantIntegrations,
        setWaModules,
        setSelectedWaModuleId,
        setCustomers,
        setSelectedCustomerId
    });
    const {
        currentUserCapabilities,
        scopedUsers,
        selectedUser,
        selectedUserRole,
        selectedUserRolePriority,
        selectedUserIsSelf,
        canEditSelectedUser,
        canEditSelectedUserRole,
        canToggleSelectedUserStatus,
        canEditSelectedUserOptionalAccess,
        canEditRoleInUserForm,
        canEditScopeInUserForm,
        canConfigureOptionalAccessInUserForm,
        allowedOptionalPermissionsForUserFormRole,
        allowedPackIdsForUserFormRole
    } = useSaasPanelUserScopeState({
        overviewUsers: overview.users,
        tenantScopeId,
        selectedUserId,
        currentUserId,
        actorRoleForPolicy,
        actorRolePriority,
        canManageUsers,
        canActorManageRoleChanges,
        canEditOptionalAccess,
        userPanelMode,
        userFormRole: userForm.role,
        canManageTenants,
        canManageCatalog,
        canManageLabels,
        canManageTenantSettings,
        canEditModules,
        canViewSuperAdminSections,
        resolvePrimaryRoleFromMemberships,
        sanitizeMemberships,
        getRolePriority,
        getOptionalPermissionKeysForRole,
        getAllowedPackIdsForRole
    });
    const {
        filteredCustomers,
        selectedCustomer,
        selectedWaModule,
        quickReplyScopeModuleId,
        quickReplyLibrariesByScope,
        selectedQuickReplyLibrary,
        quickReplyItemsForSelectedLibrary,
        selectedQuickReplyItem,
        selectedQuickReplyItemMediaAssets,
        quickReplyItemFormAssets,
        visibleQuickReplyLibraries,
        visibleQuickReplyItemsForSelectedLibrary,
        tenantLabelItems,
        selectedTenantLabel,
        visibleTenantLabels,
        selectedSettingsTenant,
        quickReplyTenantPlanId,
        quickReplyUploadMaxMb,
        quickReplyStorageQuotaMb,
        quickReplyUploadMaxBytes,
        selectedConfigModule,
        activeQuickReplyLibraries,
        moduleQuickReplySourceModuleId,
        moduleQuickReplyAssignedLibraries,
        moduleQuickReplyAssignedLibraryIds,
        tenantCatalogItems,
        selectedTenantCatalog,
        selectedCatalogProduct,
        activeCatalogOptions,
        activeCatalogLabelMap,
        tenantAiAssistantItems,
        activeAiAssistantOptions,
        selectedAiAssistant,
        defaultAiAssistantId,
        aiAssistantLabelMap,
        planIds,
        selectedPlan
    } = useSaasPanelDerivedData({
        customerSearch,
        customers,
        selectedCustomerId,
        waModules,
        selectedWaModuleId,
        quickReplyModuleFilterId,
        quickReplyLibraries,
        selectedQuickReplyLibraryId,
        quickReplyItems,
        selectedQuickReplyItemId,
        quickReplyItemForm,
        quickReplyLibrarySearch,
        quickReplyItemSearch,
        tenantLabels,
        selectedLabelId,
        labelSearch,
        tenantOptions,
        settingsTenantId,
        planMatrix,
        quickReplyDefaultMaxUploadMb: QUICK_REPLY_DEFAULT_MAX_UPLOAD_MB,
        quickReplyDefaultStorageMb: QUICK_REPLY_DEFAULT_STORAGE_MB,
        selectedConfigKey,
        waModuleForm,
        tenantCatalogs,
        selectedCatalogId,
        tenantCatalogProducts,
        selectedCatalogProductId,
        tenantAiAssistants,
        selectedAiAssistantId,
        selectedPlanId,
        planOptions: PLAN_OPTIONS
    });
    const {
        usersByTenant,
        usersForSettingsTenant,
        assignedModuleUsers,
        availableUsersForModulePicker
    } = useSaasTenantUsers({
        overviewUsers: overview.users,
        settingsTenantId,
        waModuleForm,
        toUserDisplayName
    });
    const {
        uploadingQuickReplyAssets,
        handleQuickReplyAssetSelection,
        removeQuickReplyAssetAt
    } = useQuickReplyAssetsUpload({
        requestJson,
        settingsTenantId,
        selectedQuickReplyLibrary,
        quickReplyUploadMaxBytes,
        quickReplyUploadMaxMb,
        setQuickReplyItemForm
    });
    const {
        loadQuickReplyData,
        openQuickReplyLibraryCreate,
        openQuickReplyLibraryEdit,
        cancelQuickReplyLibraryEdit,
        toggleModuleInQuickReplyLibraryForm,
        saveQuickReplyLibrary,
        deactivateQuickReplyLibrary,
        openQuickReplyItemCreate,
        openQuickReplyItemEdit,
        cancelQuickReplyItemEdit,
        saveQuickReplyItem,
        deactivateQuickReplyItem
    } = useQuickReplyAdminActions({
        requestJson,
        settingsTenantId,
        waModules,
        selectedQuickReplyLibrary,
        selectedQuickReplyLibraryId,
        selectedQuickReplyItem,
        selectedQuickReplyItemId,
        quickReplyScopeModuleId,
        quickReplyLibraryForm,
        quickReplyItemForm,
        quickReplyLibraryPanelMode,
        quickReplyItemPanelMode,
        emptyQuickReplyLibraryForm: EMPTY_QUICK_REPLY_LIBRARY_FORM,
        emptyQuickReplyItemForm: EMPTY_QUICK_REPLY_ITEM_FORM,
        setQuickReplyLibraries,
        setQuickReplyItems,
        setSelectedQuickReplyLibraryId,
        setSelectedQuickReplyItemId,
        setQuickReplyModuleFilterId,
        setQuickReplyLibraryForm,
        setQuickReplyItemForm,
        setQuickReplyLibraryPanelMode,
        setQuickReplyItemPanelMode,
        setLoadingQuickReplies
    });
    const {
        loadTenantLabels,
        openTenantLabelCreate,
        openTenantLabelEdit,
        cancelTenantLabelEdit,
        toggleModuleInLabelForm,
        saveTenantLabel,
        deactivateTenantLabel
    } = useTenantLabelsActions({
        requestJson,
        settingsTenantId,
        selectedTenantLabel,
        selectedLabelId,
        labelForm,
        labelPanelMode,
        emptyLabelForm: EMPTY_LABEL_FORM,
        defaultLabelColors: DEFAULT_LABEL_COLORS,
        setTenantLabels,
        setSelectedLabelId,
        setLabelForm,
        setLabelPanelMode,
        setLoadingLabels
    });
    const { runActionProxy, setRunAction } = useSaasRunActionBridge();
    const {
        loadTenantCatalogs,
        loadTenantCatalogProducts,
        openCatalogProductCreate,
        openCatalogProductEdit,
        cancelCatalogProductEdit,
        saveCatalogProduct,
        deactivateCatalogProduct,
        handleCatalogProductImageUpload,
        openCatalogView,
        openCatalogCreate,
        openCatalogEdit,
        cancelCatalogEdit
    } = useCatalogAdminActions({
        requestJson,
        settingsTenantId,
        canEditCatalog,
        selectedTenantCatalog,
        selectedCatalogProduct,
        selectedCatalogProductId,
        catalogProductForm,
        catalogProductPanelMode,
        emptyCatalogProductForm: EMPTY_CATALOG_PRODUCT_FORM,
        emptyTenantCatalogForm: EMPTY_TENANT_CATALOG_FORM,
        setTenantCatalogs,
        setSelectedCatalogId,
        setTenantCatalogForm,
        setTenantCatalogProducts,
        setSelectedCatalogProductId,
        setCatalogProductForm,
        setCatalogProductPanelMode,
        setCatalogProductImageError,
        setCatalogProductImageUploading,
        setLoadingTenantCatalogs,
        setLoadingCatalogProducts,
        setCatalogPanelMode
    });
    const {
        loadTenantAiAssistants,
        openAiAssistantCreate,
        applyLavitatAssistantPreset,
        openAiAssistantView,
        openAiAssistantEdit,
        cancelAiAssistantEdit,
        saveAiAssistant,
        markAiAssistantAsDefault,
        toggleAiAssistantActive
    } = useAiAssistantsAdminActions({
        requestJson,
        settingsTenantId,
        canManageAi,
        selectedAiAssistant,
        selectedAiAssistantId,
        aiAssistantForm,
        aiAssistantPanelMode,
        tenantIntegrations,
        emptyAiAssistantForm: EMPTY_AI_ASSISTANT_FORM,
        setLoadingAiAssistants,
        setTenantAiAssistants,
        setSelectedAiAssistantId,
        setAiAssistantForm,
        setAiAssistantPanelMode,
        runAction: runActionProxy
    });
    const {
        loadPlanMatrix,
        loadAccessCatalog,
        openPlanView,
        openPlanEdit,
        cancelPlanEdit,
        openRoleCreate,
        openRoleView,
        openRoleEdit,
        cancelRoleEdit,
        toggleRolePermission,
        saveRoleProfile
    } = usePlansRolesAdminActions({
        requestJson,
        canManageRoles,
        selectedRoleProfile,
        selectedRoleKey,
        roleForm,
        rolePanelMode,
        selectedPlanId,
        planMatrix,
        planOptions: PLAN_OPTIONS,
        emptyRoleForm: EMPTY_ROLE_FORM,
        setLoadingPlans,
        setPlanMatrix,
        setSelectedPlanId,
        setPlanForm,
        setPlanPanelMode,
        setRolePanelMode,
        setLoadingAccessCatalog,
        setAccessCatalog,
        setSelectedRoleKey,
        setRoleForm,
        runAction: runActionProxy
    });
    const {
        openTenantCreate,
        openTenantView,
        openTenantEdit,
        cancelTenantEdit,
        openUserCreate,
        openUserView,
        openUserEdit,
        cancelUserEdit,
        updateMembershipDraft,
        removeMembershipDraft,
        addMembershipDraft
    } = useTenantsUsersAdminActions({
        loadingAccessCatalog,
        accessCatalog,
        canEditSelectedUser,
        selectedTenant,
        selectedUser,
        tenantScopeId,
        selectedTenantId,
        tenantOptions,
        roleOptions,
        emptyTenantForm: EMPTY_TENANT_FORM,
        emptyUserForm: EMPTY_USER_FORM,
        setTenantPanelMode,
        setSelectedTenantId,
        setSettingsTenantId,
        setTenantForm,
        setUserPanelMode,
        setSelectedUserId,
        setMembershipDraft,
        setUserForm,
        loadAccessCatalog
    });
    const {
        openCustomerCreate,
        openCustomerView,
        openCustomerEdit,
        cancelCustomerEdit
    } = useCustomersAdminActions({
        selectedCustomer,
        customerImportModuleId,
        emptyCustomerForm: EMPTY_CUSTOMER_FORM,
        setSelectedCustomerId,
        setCustomerPanelMode,
        setCustomerForm
    });
    const {
        isSectionEnabled,
        adminNavItems,
        selectedSectionId,
        isModulesSection,
        isCatalogSection,
        isPlansSection,
        isRolesSection,
        isCustomersSection,
        isOperationsSection,
        isAiSection,
        isLabelsSection,
        isQuickRepliesSection,
        isGeneralConfigSection
    } = useSaasPanelNavigation({
        navItems: ADMIN_NAV_ITEMS,
        currentSection,
        activeSection,
        initialSection,
        canManageTenants,
        canManageUsers,
        canViewCustomers,
        canViewOperations,
        canViewAi,
        canViewLabels,
        canViewQuickReplies,
        canViewModules,
        canManageCatalog,
        canViewSuperAdminSections,
        canViewTenantSettings
    });


    const assignmentRoleOptions = ['seller', 'admin', 'owner'];

    const {
        operationTenantId,
        hasActiveModuleForOperation,
        canOpenOperation
    } = useSaasOperationAccess({
        requiresTenantSelection,
        settingsTenantId,
        tenantScopeId,
        activeTenantId,
        waModules,
        onOpenWhatsAppOperation
    });
    const scrollToSection = (sectionId, behavior = 'smooth') => {
        const cleanSection = String(sectionId || '').trim();
        if (!cleanSection) return;
        const node = document.getElementById(cleanSection);
        if (node && typeof node.scrollIntoView === 'function') {
            node.scrollIntoView({ behavior, block: 'start' });
        }
    };

    const {
        resetWaModuleForm,
        openWaModuleEditor,
        clearConfigSelection,
        openConfigModuleCreate,
        openConfigModuleEdit,
        openConfigModuleView,
        openConfigSettingsEdit,
        openConfigSettingsView,
        syncQuickReplyLibrariesForModule,
        toggleAssignedUserForModule,
        toggleCatalogForModule,
        toggleQuickReplyLibraryForModuleDraft,
        handleSectionChange
    } = useSaasModuleSectionActions({
        waModuleEditor: {
            quickReplyLibraries,
            emptyWaModuleForm: EMPTY_WA_MODULE_FORM,
            emptyIntegrationsForm: EMPTY_INTEGRATIONS_FORM,
            emptyTenantCatalogForm: EMPTY_TENANT_CATALOG_FORM,
            emptyCustomerForm: EMPTY_CUSTOMER_FORM,
            emptyAiAssistantForm: EMPTY_AI_ASSISTANT_FORM,
            emptyRoleForm: EMPTY_ROLE_FORM,
            normalizePlanForm,
            setWaModuleForm,
            setTenantIntegrations,
            setTenantCatalogForm,
            setSelectedPlanId,
            setPlanForm,
            setRoleForm,
            setEditingWaModuleId,
            setModuleUserPickerId,
            setModuleQuickReplyLibraryDraft,
            setSelectedCustomerId,
            setCustomerPanelMode,
            setCustomerForm,
            setCustomerSearch,
            setCustomerCsvText,
            setSelectedAiAssistantId,
            setAiAssistantPanelMode,
            setAiAssistantForm,
            setCustomerImportModuleId,
            setSelectedWaModuleId
        },
        moduleConfig: {
            requestJson,
            settingsTenantId,
            canEditTenantSettings,
            canEditModules,
            waModules,
            selectedConfigModule,
            quickReplyLibraries,
            activeCatalogOptions,
            defaultAiAssistantId,
            setSelectedConfigKey,
            setSelectedRoleKey,
            setSelectedWaModuleId,
            setTenantSettingsPanelMode,
            setWaModulePanelMode,
            setCatalogPanelMode,
            setModuleUserPickerId,
            setModuleQuickReplyLibraryDraft,
            setWaModuleForm
        },
        sectionChange: {
            isSectionEnabled,
            setSelectedTenantId,
            setTenantPanelMode,
            setSelectedUserId,
            setUserPanelMode,
            setMembershipDraft,
            setSelectedRoleKey,
            setRolePanelMode,
            setRoleForm,
            emptyRoleForm: EMPTY_ROLE_FORM,
            setSelectedCustomerId,
            setCustomerPanelMode,
            setSelectedAiAssistantId,
            setAiAssistantPanelMode,
            setAiAssistantForm,
            emptyAiAssistantForm: EMPTY_AI_ASSISTANT_FORM,
            setSelectedLabelId,
            setLabelPanelMode,
            setLabelForm,
            emptyLabelForm: EMPTY_LABEL_FORM,
            setSelectedQuickReplyLibraryId,
            setSelectedQuickReplyItemId,
            setQuickReplyModuleFilterId,
            setQuickReplyLibraryPanelMode,
            setQuickReplyItemPanelMode,
            setQuickReplyLibraryForm,
            emptyQuickReplyLibraryForm: EMPTY_QUICK_REPLY_LIBRARY_FORM,
            setQuickReplyItemForm,
            emptyQuickReplyItemForm: EMPTY_QUICK_REPLY_ITEM_FORM,
            setCurrentSection
        }
    });
    const {
        runAction,
        handleOpenOperation,
        handleFormImageUpload,
        clearPanelSelection,
        panelHasSelection,
        openTenantFromUserMembership,
        openUserFromTenant
    } = useSaasPanelLifecycle({
        bootstrap: {
            actions: {
                requestJson,
                onOpenWhatsAppOperation,
                operationTenantId,
                tenantScopeId,
                activeTenantId,
                selectedTenantId,
                setError,
                setBusy,
                refreshOverview,
                settingsTenantId,
                loadTenantSettings,
                loadWaModules,
                loadTenantCatalogs,
                loadTenantAiAssistants,
                loadQuickReplyData,
                loadTenantLabels
            },
            loadEffects: {
                isOpen,
                canManageSaas,
                canViewSuperAdminSections,
                tenantScopeId,
                refreshOverview,
                loadAccessCatalog,
                loadPlanMatrix,
                loadTenantSettings,
                loadWaModules,
                loadTenantCatalogs,
                loadTenantAiAssistants,
                loadTenantIntegrations,
                loadCustomers,
                loadQuickReplyData,
                loadTenantLabels,
                loadTenantAssignmentRules,
                loadTenantOperationsKpis,
                setError
            },
            setRunAction
        },
        selection: {
            selectedTenantId,
            selectedUserId,
            selectedWaModuleId,
            selectedCatalogId,
            selectedCatalogProductId,
            selectedConfigKey,
            selectedRoleKey,
            selectedPlanId,
            selectedCustomerId,
            selectedAiAssistantId,
            selectedLabelId,
            tenantPanelMode,
            userPanelMode,
            tenantSettingsPanelMode,
            waModulePanelMode,
            catalogPanelMode,
            catalogProductPanelMode,
            planPanelMode,
            rolePanelMode,
            customerPanelMode,
            aiAssistantPanelMode,
            labelPanelMode,
            emptyTenantForm: EMPTY_TENANT_FORM,
            emptyUserForm: EMPTY_USER_FORM,
            emptyWaModuleForm: EMPTY_WA_MODULE_FORM,
            emptyIntegrationsForm: EMPTY_INTEGRATIONS_FORM,
            emptyTenantCatalogForm: EMPTY_TENANT_CATALOG_FORM,
            emptyCatalogProductForm: EMPTY_CATALOG_PRODUCT_FORM,
            emptyAiAssistantForm: EMPTY_AI_ASSISTANT_FORM,
            emptyQuickReplyLibraryForm: EMPTY_QUICK_REPLY_LIBRARY_FORM,
            emptyQuickReplyItemForm: EMPTY_QUICK_REPLY_ITEM_FORM,
            emptyLabelForm: EMPTY_LABEL_FORM,
            emptyRoleForm: EMPTY_ROLE_FORM,
            normalizePlanForm,
            setSelectedTenantId,
            setSelectedUserId,
            setSelectedWaModuleId,
            setSelectedCatalogId,
            setSelectedCatalogProductId,
            setSelectedConfigKey,
            setTenantPanelMode,
            setUserPanelMode,
            setTenantSettingsPanelMode,
            setWaModulePanelMode,
            setCatalogPanelMode,
            setCatalogProductPanelMode,
            setPlanPanelMode,
            setRolePanelMode,
            setMembershipDraft,
            setTenantForm,
            setUserForm,
            setWaModuleForm,
            setTenantIntegrations,
            setTenantCatalogForm,
            setTenantCatalogProducts,
            setCatalogProductForm,
            setCatalogProductImageError,
            setSelectedAiAssistantId,
            setAiAssistantForm,
            setAiAssistantPanelMode,
            setSelectedQuickReplyLibraryId,
            setSelectedQuickReplyItemId,
            setQuickReplyModuleFilterId,
            setQuickReplyLibraryForm,
            setQuickReplyItemForm,
            setQuickReplyLibraryPanelMode,
            setQuickReplyItemPanelMode,
            setSelectedLabelId,
            setLabelForm,
            setLabelPanelMode,
            setLabelSearch,
            setSelectedPlanId,
            setPlanForm,
            setRoleForm,
            setEditingWaModuleId,
            setModuleUserPickerId,
            setModuleQuickReplyLibraryDraft
        },
        hotkeys: {
            isOpen
        },
        tenantScopeEffects: {
            isOpen,
            tenantScopeId,
            requiresTenantSelection,
            settingsTenantId,
            activeTenantId,
            tenantOptions,
            launchSource,
            preferredTenantId,
            emptyTenantCatalogForm: EMPTY_TENANT_CATALOG_FORM,
            emptyCatalogProductForm: EMPTY_CATALOG_PRODUCT_FORM,
            emptyAiAssistantForm: EMPTY_AI_ASSISTANT_FORM,
            emptyQuickReplyLibraryForm: EMPTY_QUICK_REPLY_LIBRARY_FORM,
            emptyQuickReplyItemForm: EMPTY_QUICK_REPLY_ITEM_FORM,
            emptyLabelForm: EMPTY_LABEL_FORM,
            resetOperationsState,
            setWaModules,
            setSelectedWaModuleId,
            setTenantCatalogs,
            setSelectedCatalogId,
            setTenantCatalogForm,
            setTenantCatalogProducts,
            setSelectedCatalogProductId,
            setCatalogProductForm,
            setCatalogProductPanelMode,
            setCatalogProductImageError,
            setTenantAiAssistants,
            setSelectedAiAssistantId,
            setAiAssistantForm,
            setAiAssistantPanelMode,
            setQuickReplyLibraries,
            setQuickReplyItems,
            setSelectedQuickReplyLibraryId,
            setSelectedQuickReplyItemId,
            setQuickReplyModuleFilterId,
            setQuickReplyLibraryForm,
            setQuickReplyItemForm,
            setQuickReplyLibraryPanelMode,
            setQuickReplyItemPanelMode,
            setTenantLabels,
            setSelectedLabelId,
            setLabelForm,
            setLabelPanelMode,
            setSelectedConfigKey,
            setSelectedRoleKey,
            setTenantSettingsPanelMode,
            setWaModulePanelMode,
            setCatalogPanelMode,
            setModuleUserPickerId,
            setSelectedCustomerId,
            setCustomerPanelMode,
            setCustomerSearch,
            setCustomerCsvText,
            setLabelSearch,
            setSettingsTenantId,
            setSelectedTenantId,
            setCurrentSection
        },
        sectionSyncEffects: {
            isOpen,
            canManageSaas,
            initialSection,
            activeSection,
            selectedPlanId,
            planMatrix,
            selectedConfigKey,
            selectedConfigModule,
            normalizePlanForm,
            setPlanForm,
            setCurrentSection,
            setSelectedConfigKey,
            setSelectedRoleKey,
            setSelectedWaModuleId,
            setWaModulePanelMode,
            resetWaModuleForm
        },
        formSyncEffects: {
            isOpen,
            settingsTenantId,
            selectedTenant,
            tenantPanelMode,
            selectedUser,
            userPanelMode,
            selectedCustomer,
            customerPanelMode,
            selectedAiAssistant,
            aiAssistantPanelMode,
            selectedTenantCatalog,
            catalogPanelMode,
            selectedWaModule,
            selectedQuickReplyLibrary,
            quickReplyLibraryPanelMode,
            selectedQuickReplyItem,
            selectedQuickReplyLibraryEntity: selectedQuickReplyLibrary,
            quickReplyItemPanelMode,
            quickReplyScopeModuleId,
            emptyTenantForm: EMPTY_TENANT_FORM,
            emptyUserForm: EMPTY_USER_FORM,
            emptyCustomerForm: EMPTY_CUSTOMER_FORM,
            emptyAiAssistantForm: EMPTY_AI_ASSISTANT_FORM,
            emptyTenantCatalogForm: EMPTY_TENANT_CATALOG_FORM,
            emptyCatalogProductForm: EMPTY_CATALOG_PRODUCT_FORM,
            emptyQuickReplyLibraryForm: EMPTY_QUICK_REPLY_LIBRARY_FORM,
            emptyQuickReplyItemForm: EMPTY_QUICK_REPLY_ITEM_FORM,
            buildTenantFormFromItem,
            buildUserFormFromItem,
            normalizeCustomerFormFromItem,
            buildAiAssistantFormFromItem,
            buildTenantCatalogFormFromItem,
            normalizeQuickReplyMediaAssets,
            loadTenantCatalogProducts,
            setError,
            resetWaModuleForm,
            openWaModuleEditor,
            setTenantForm,
            setUserForm,
            setCustomerForm,
            setAiAssistantForm,
            setTenantCatalogForm,
            setTenantCatalogProducts,
            setSelectedCatalogProductId,
            setCatalogProductForm,
            setCatalogProductPanelMode,
            setCatalogProductImageError,
            setQuickReplyLibraryForm,
            setQuickReplyItemForm
        },
        crossNavigation: {
            openTenantView,
            openUserView,
            setCurrentSection,
            scrollToSection
        }
    });

    if (!isOpen) return null;

    const handlePanelClose = () => {
        if (typeof onLogout === 'function') {
            onLogout();
            return;
        }
        onClose?.();
    };

    const handleTenantChange = (nextTenantId) => {
        setSettingsTenantId(nextTenantId);
        if (nextTenantId) setSelectedTenantId(nextTenantId);
    };

    const handleTenantClear = () => {
        setSettingsTenantId('');
        setSelectedTenantId('');
    };

    const frameProps = {
        embedded,
        showHeader,
        title: 'Control SaaS',
        subtitle: `Empresa activa: ${activeTenantLabel}`,
        canOpenOperation,
        isBusy: busy,
        onOpenOperation: handleOpenOperation,
        currentUserAvatarUrl,
        currentUserDisplayName,
        currentUserRoleLabel,
        buildInitials,
        closeLabel,
        onClose: handlePanelClose,
        error,
        showPanelLoading,
        requiresTenantSelection,
        settingsTenantId,
        tenantOptions,
        toTenantDisplayName,
        onChangeTenant: handleTenantChange,
        onClearTenant: handleTenantClear,
        showNavigation,
        adminNavItems,
        selectedSectionId,
        tenantScopeLocked,
        onSectionChange: handleSectionChange
    };

    if (!canManageSaas) {
        return (
            <SaasPanelNoAccess
                embedded={embedded}
                showHeader={showHeader}
                canOpenOperation={canOpenOperation}
                isBusy={busy}
                onOpenOperation={handleOpenOperation}
                currentUserAvatarUrl={currentUserAvatarUrl}
                currentUserDisplayName={currentUserDisplayName}
                currentUserRoleLabel={currentUserRoleLabel}
                buildInitials={buildInitials}
                closeLabel={closeLabel}
                onClose={handlePanelClose}
            />
        );
    }

    const entitySectionsContext = {
        selectedSectionId,
        currentUserAvatarUrl,
        buildInitials,
        currentUserDisplayName,
        currentUserRoleLabel,
        currentUserEmail,
        activeTenantLabel,
        currentUserTenantCount,
        currentUserCapabilities,
        tenantScopeLocked,
        tenantScopeId,
        tenantOptions,
        overview,
        scopedUsers,
        waModules,
        busy,
        isSectionEnabled,
        handleSectionChange,
        canManageTenants,
        openTenantCreate,
        selectedTenantId,
        openTenantView,
        selectedTenant,
        tenantPanelMode,
        openTenantEdit,
        runAction,
        requestJson,
        activeTenantId,
        setSettingsTenantId,
        setSelectedTenantId,
        setTenantPanelMode,
        setTenantForm,
        cancelTenantEdit,
        PLAN_OPTIONS,
        tenantForm,
        handleFormImageUpload,
        toTenantDisplayName,
        formatDateTimeLabel,
        usersByTenant,
        toUserDisplayName,
        openUserFromTenant,
        aiUsageByTenant,
        settingsTenantId,
        canManageUsers,
        openUserCreate,
        hasAccessCatalogData,
        loadingAccessCatalog,
        selectedUserId,
        userPanelMode,
        openUserView,
        selectedUser,
        canEditSelectedUser,
        canToggleSelectedUserStatus,
        openUserEdit,
        canEditScopeInUserForm,
        openTenantFromUserMembership,
        userForm,
        setUserForm,
        roleOptions,
        canEditRoleInUserForm,
        canEditOptionalAccess,
        allowedOptionalPermissionsForUserFormRole,
        permissionLabelMap,
        getOptionalPermissionKeysForRole,
        accessPackOptions,
        accessPackLabelMap,
        getAllowedPackIdsForRole,
        allowedPackIdsForUserFormRole,
        canConfigureOptionalAccessInUserForm,
        roleLabelMap,
        sanitizeMemberships,
        setSelectedUserId,
        setUserPanelMode,
        cancelUserEdit,
        isCustomersSection,
        filteredCustomers,
        openCustomerCreate,
        customerSearch,
        setCustomerSearch,
        selectedCustomerId,
        customerPanelMode,
        openCustomerView,
        selectedCustomer,
        openCustomerEdit,
        loadCustomers,
        customerForm,
        setCustomerForm,
        buildCustomerPayloadFromForm,
        setCustomerPanelMode,
        cancelCustomerEdit,
        customerImportModuleId,
        setCustomerImportModuleId,
        customerCsvText,
        setCustomerCsvText
    };

    const opsAndAutomationSectionsContext = {
        isOperationsSection,
        tenantScopeLocked,
        busy,
        loadingAssignmentRules,
        loadingOperationsKpis,
        canManageAssignments,
        canViewOperations,
        assignmentRules,
        assignmentRoleOptions,
        operationsSnapshot,
        activeTenantChatCandidates: unassignedCandidates,
        tenantScopeId,
        setAssignmentRules,
        runAction,
        saveAssignmentRules,
        loadTenantOperationsKpis,
        triggerAutoAssignPreview,
        formatDateTimeLabel,
        isAiSection,
        loadingAiAssistants,
        settingsTenantId,
        loadTenantAiAssistants,
        openAiAssistantCreate,
        tenantAiAssistantItems,
        selectedAiAssistantId,
        aiAssistantPanelMode,
        openAiAssistantView,
        selectedAiAssistant,
        canManageAi,
        openAiAssistantEdit,
        markAiAssistantAsDefault,
        toggleAiAssistantActive,
        aiAssistantForm,
        setAiAssistantForm,
        AI_MODEL_OPTIONS,
        applyLavitatAssistantPreset,
        saveAiAssistant,
        cancelAiAssistantEdit,
        setSelectedAiAssistantId,
        setAiAssistantPanelMode,
        EMPTY_AI_ASSISTANT_FORM,
        isLabelsSection,
        loadingLabels,
        loadTenantLabels,
        setError,
        canManageLabels,
        openTenantLabelCreate,
        labelSearch,
        setLabelSearch,
        visibleTenantLabels,
        selectedTenantLabel,
        labelPanelMode,
        setSelectedLabelId,
        setLabelPanelMode,
        openTenantLabelEdit,
        deactivateTenantLabel,
        requestJson,
        buildTenantLabelPayload,
        labelForm,
        setLabelForm,
        normalizeTenantLabelColor,
        DEFAULT_LABEL_COLORS,
        toggleModuleInLabelForm,
        saveTenantLabel,
        cancelTenantLabelEdit,
        isQuickRepliesSection,
        loadingQuickReplies,
        loadQuickReplyData,
        canManageQuickReplies,
        openQuickReplyLibraryCreate,
        quickReplyModuleFilterId,
        setQuickReplyModuleFilterId,
        setSelectedQuickReplyLibraryId,
        setSelectedQuickReplyItemId,
        setQuickReplyLibraryPanelMode,
        setQuickReplyItemPanelMode,
        waModules,
        quickReplyLibrarySearch,
        setQuickReplyLibrarySearch,
        visibleQuickReplyLibraries,
        selectedQuickReplyLibrary,
        quickReplyLibraryPanelMode,
        openQuickReplyLibraryEdit,
        deactivateQuickReplyLibrary,
        quickReplyLibraryForm,
        setQuickReplyLibraryForm,
        toggleModuleInQuickReplyLibraryForm,
        saveQuickReplyLibrary,
        cancelQuickReplyLibraryEdit,
        QUICK_REPLY_ALLOWED_EXTENSIONS_LABEL,
        visibleQuickReplyItemsForSelectedLibrary,
        quickReplyUploadMaxMb,
        quickReplyStorageQuotaMb,
        quickReplyItemSearch,
        setQuickReplyItemSearch,
        normalizeQuickReplyMediaAssets,
        selectedQuickReplyItem,
        quickReplyItemPanelMode,
        openQuickReplyItemEdit,
        deactivateQuickReplyItem,
        selectedQuickReplyItemMediaAssets,
        resolveQuickReplyAssetPreviewUrl,
        getQuickReplyAssetDisplayName,
        isQuickReplyImageAsset,
        getQuickReplyAssetTypeLabel,
        formatBytes,
        quickReplyItemForm,
        setQuickReplyItemForm,
        uploadingQuickReplyAssets,
        QUICK_REPLY_ACCEPT_VALUE,
        handleQuickReplyAssetSelection,
        quickReplyItemFormAssets,
        removeQuickReplyAssetAt,
        saveQuickReplyItem,
        cancelQuickReplyItemEdit,
        openQuickReplyItemCreate
    };

    const configAndGovernanceSectionsContext = {
        isGeneralConfigSection,
        isModulesSection,
        settingsTenantId,
        toTenantDisplayName,
        tenantOptions,
        busy,
        canEditModules,
        openConfigModuleCreate,
        openConfigSettingsView,
        clearConfigSelection,
        tenantSettings,
        MODULE_KEYS,
        waModules,
        selectedConfigKey,
        openConfigModuleView,
        waModulePanelMode,
        selectedConfigModule,
        assignedModuleUsers,
        toUserDisplayName,
        usersForSettingsTenant,
        normalizeCatalogIdsList,
        activeCatalogLabelMap,
        sanitizeAiAssistantCode,
        aiAssistantLabelMap,
        handleOpenOperation,
        openConfigModuleEdit,
        runAction,
        requestJson,
        tenantSettingsPanelMode,
        CATALOG_MODE_OPTIONS,
        formatDateTimeLabel,
        buildInitials,
        waModuleForm,
        setWaModuleForm,
        availableUsersForModulePicker,
        toggleAssignedUserForModule,
        activeCatalogOptions,
        toggleCatalogForModule,
        activeAiAssistantOptions,
        moduleQuickReplyLibraryDraft,
        activeQuickReplyLibraries,
        toggleQuickReplyLibraryForModuleDraft,
        moduleUserPickerId,
        setModuleUserPickerId,
        syncQuickReplyLibrariesForModule,
        handleFormImageUpload,
        setWaModulePanelMode,
        setSelectedWaModuleId,
        setSelectedConfigKey,
        isCatalogSection,
        loadingTenantCatalogs,
        loadTenantCatalogs,
        canEditCatalog,
        openCatalogCreate,
        tenantCatalogItems,
        selectedTenantCatalog,
        openCatalogView,
        catalogPanelMode,
        setCatalogPanelMode,
        setTenantCatalogForm,
        EMPTY_TENANT_CATALOG_FORM,
        cancelCatalogEdit,
        openCatalogEdit,
        buildTenantCatalogPayload,
        selectedCatalogProductId,
        setSelectedCatalogProductId,
        loadTenantCatalogProducts,
        tenantCatalogProducts,
        loadingCatalogProducts,
        setCatalogProductPanelMode,
        openCatalogProductCreate,
        selectedCatalogProduct,
        catalogProductPanelMode,
        openCatalogProductEdit,
        deactivateCatalogProduct,
        setCatalogProductForm,
        buildCatalogProductFormFromItem,
        catalogProductForm,
        setCatalogProductImageError,
        handleCatalogProductImageUpload,
        catalogProductImageUploading,
        catalogProductImageError,
        saveCatalogProduct,
        cancelCatalogProductEdit,
        setSelectedCatalogId,
        tenantCatalogForm,
        isRolesSection,
        canManageRoles,
        openRoleCreate,
        roleProfiles,
        selectedRoleKey,
        rolePanelMode,
        openRoleView,
        selectedRoleProfile,
        openRoleEdit,
        permissionLabelMap,
        rolePermissionOptions,
        roleForm,
        setRoleForm,
        sanitizeRoleCode,
        toggleRolePermission,
        saveRoleProfile,
        cancelRoleEdit,
        isPlansSection,
        loadingPlans,
        loadPlanMatrix,
        planIds,
        selectedPlanId,
        planMatrix,
        openPlanView,
        selectedPlan,
        planPanelMode,
        openPlanEdit,
        PLAN_LIMIT_KEYS,
        PLAN_FEATURE_KEYS,
        planForm,
        setPlanForm,
        chunkItems,
        setPlanPanelMode,
        cancelPlanEdit
    };

    return (
        <SaasPanelFrame {...frameProps}>
            <SaasPanelEntitySections context={entitySectionsContext} />
            {selectedSectionId !== 'saas_resumen' && (
                <div className="saas-admin-grid">
                    <SaasPanelOpsAndAutomationSections context={opsAndAutomationSectionsContext} />
                    <SaasPanelConfigAndGovernanceSections context={configAndGovernanceSectionsContext} />
                </div>
            )}
        </SaasPanelFrame>
    );
}




















