module.exports = {
    messageHistoryService: require('./message-history.service'),
    conversationOpsService: require('./conversation-ops.service'),
    chatCommercialStatusService: require('./chat-commercial-status.service'),
    customerConsentService: require('./customer-consent.service'),
    chatOriginService: require('./chat-origin.service'),
    templateWebhookEventsService: require('./template-webhook-events.service'),
    campaignQueueService: require('./campaign-queue.service'),
    campaignDispatcherJobService: require('./campaign-dispatcher-job.service'),
    chatAssignmentPolicyService: require('./chat-assignment-policy.service'),
    assignmentRulesService: require('./assignment-rules.service'),
    chatAssignmentRouterService: require('./chat-assignment-router.service'),
    chatAssignmentInactivityJobService: require('./chat-assignment-inactivity-job.service'),
    customerModuleContextsService: require('./customer-module-contexts.service'),
    metaTemplatesService: require('./meta-templates.service'),
    templateVariablesService: require('./template-variables.service'),
    operationsKpiService: require('./operations-kpi.service'),
    aiChatHistoryService: require('./ai-chat-history.service'),
    opsTelemetry: require('./ops-telemetry.service'),
    aiService: require('./ai.service'),
    aiPromptContextService: require('./ai-prompt-context.service')
};
